// Mocks generated by Mockito 5.4.5 from annotations
// in ray_club_app/test/features/goals/create_goal_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:ray_club_app/features/auth/repositories/auth_repository.dart'
    as _i6;
import 'package:ray_club_app/features/goals/models/unified_goal_model.dart'
    as _i2;
import 'package:ray_club_app/features/goals/repositories/unified_goal_repository.dart'
    as _i4;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnifiedGoal_0 extends _i1.SmartFake implements _i2.UnifiedGoal {
  _FakeUnifiedGoal_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UnifiedGoalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnifiedGoalRepository extends _i1.Mock
    implements _i4.UnifiedGoalRepository {
  MockUnifiedGoalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.UnifiedGoal>> getUserGoals(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGoals,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i2.UnifiedGoal>>.value(<_i2.UnifiedGoal>[]),
      ) as _i5.Future<List<_i2.UnifiedGoal>>);

  @override
  _i5.Future<List<_i2.UnifiedGoal>> getActiveGoals(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveGoals,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i2.UnifiedGoal>>.value(<_i2.UnifiedGoal>[]),
      ) as _i5.Future<List<_i2.UnifiedGoal>>);

  @override
  _i5.Future<_i2.UnifiedGoal> createGoal(_i2.UnifiedGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGoal,
          [goal],
        ),
        returnValue: _i5.Future<_i2.UnifiedGoal>.value(_FakeUnifiedGoal_0(
          this,
          Invocation.method(
            #createGoal,
            [goal],
          ),
        )),
      ) as _i5.Future<_i2.UnifiedGoal>);

  @override
  _i5.Future<_i2.UnifiedGoal> updateGoal(_i2.UnifiedGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGoal,
          [goal],
        ),
        returnValue: _i5.Future<_i2.UnifiedGoal>.value(_FakeUnifiedGoal_0(
          this,
          Invocation.method(
            #updateGoal,
            [goal],
          ),
        )),
      ) as _i5.Future<_i2.UnifiedGoal>);

  @override
  _i5.Future<void> deleteGoal(String? goalId) => (super.noSuchMethod(
        Invocation.method(
          #deleteGoal,
          [goalId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementGoalProgress(
    String? goalId,
    double? increment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementGoalProgress,
          [
            goalId,
            increment,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.UnifiedGoal>> getGoalsForWorkoutCategory(
    String? userId,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGoalsForWorkoutCategory,
          [
            userId,
            category,
          ],
        ),
        returnValue:
            _i5.Future<List<_i2.UnifiedGoal>>.value(<_i2.UnifiedGoal>[]),
      ) as _i5.Future<List<_i2.UnifiedGoal>>);

  @override
  _i5.Future<void> updateGoalsFromWorkout(
    String? userId,
    String? workoutType,
    int? durationMinutes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGoalsFromWorkout,
          [
            userId,
            workoutType,
            durationMinutes,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i6.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i3.User?>.value(),
      ) as _i5.Future<_i3.User?>);

  @override
  _i5.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> isEmailRegistered(String? email) => (super.noSuchMethod(
        Invocation.method(
          #isEmailRegistered,
          [email],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.User> signUp(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i5.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #signUp,
            [
              email,
              password,
              name,
            ],
          ),
        )),
      ) as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.User>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfile({
    String? name,
    String? photoUrl,
    bool? onboardingSeen,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #name: name,
            #photoUrl: photoUrl,
            #onboardingSeen: onboardingSeen,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Session?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i3.Session?>.value(),
      ) as _i5.Future<_i3.Session?>);

  @override
  _i5.Future<_i3.Session?> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i5.Future<_i3.Session?>.value(),
      ) as _i5.Future<_i3.Session?>);

  @override
  _i5.Future<_i3.User?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.User?>.value(),
      ) as _i5.Future<_i3.User?>);

  @override
  _i5.Future<void> refreshSession() => (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resendVerificationEmail(
    String? email,
    String? redirectUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerificationEmail,
          [
            email,
            redirectUrl,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
