-- Continuação das receitas da Bruna Braga Nutrição + RayClub (Parte 5 - Final)

-- Receita 51: Picolé de Frutas
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Picolé de Frutas',
    'Picolé natural e refrescante',
    'Sobremesas',
    'https://images.unsplash.com/photo-1488900128323-21503983a07e',
    10,
    50,
    4,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 banana madura',
        '1/2 xícara de morangos picados',
        '1/2 xícara de suco de laranja natural',
        '1 colher de chá de mel (opcional)'
    ],
    ARRAY[
        'Bata todos os ingredientes no liquidificador até ficar homogêneo.',
        'Despeje a mistura em forminhas de picolé.',
        'Leve ao congelador por 4-6 horas ou até ficarem firmes.',
        'Retire da forma e sirva.'
    ],
    'Opção saudável para matar a vontade de doce!',
    ARRAY['sobremesa', 'refrescante', 'natural'],
    '{"Proteínas": "1g", "Carboidratos": "12g", "Gorduras": "0g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Low Carb']
);

-- Receita 52: Sorvete de Iogurte com Whey
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Sorvete de Iogurte com Whey',
    'Sorvete proteico e cremoso',
    'Sobremesas',
    'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f',
    10,
    140,
    4,
    'Fácil',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '1 xícara de iogurte grego natural sem açúcar',
        '1 scoop de whey protein (preferencialmente sabor baunilha)',
        '2 colheres de sopa de mel',
        '1/2 colher de chá de essência de baunilha'
    ],
    ARRAY[
        'Em uma tigela, misture o iogurte, o whey, o mel e a essência de baunilha.',
        'Despeje a mistura em um recipiente próprio para congelar e leve ao congelador por 3-4 horas.',
        'Retire do congelador e deixe descansar por alguns minutos antes de servir.'
    ],
    'Perfeito para o pós-treino!',
    ARRAY['proteico', 'sorvete', 'pós-treino'],
    '{"Proteínas": "20g", "Carboidratos": "15g", "Gorduras": "3g", "Fibras": "0g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY['Pós treino'],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 53: Sorbet de Morango e Banana
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Sorbet de Morango e Banana',
    'Sobremesa gelada e natural',
    'Sobremesas',
    'https://images.unsplash.com/photo-1488900128323-21503983a07e',
    10,
    80,
    4,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 banana madura congelada',
        '1 xícara de morangos congelados',
        '1 colher de sopa de mel (opcional)',
        'Suco de 1/2 limão'
    ],
    ARRAY[
        'Coloque os morangos, a banana, o mel e o suco de limão em um processador de alimentos.',
        'Processe até ficar com uma consistência cremosa, similar a um sorvete.',
        'Se necessário, adicione um pouco de água para ajudar a bater.',
        'Sirva imediatamente ou leve ao congelador para firmar mais.'
    ],
    'Sobremesa sem culpa!',
    ARRAY['natural', 'sorbet', 'frutas'],
    '{"Proteínas": "1g", "Carboidratos": "18g", "Gorduras": "0g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Vegano', 'Low Carb']
);

-- Receita 54: Pizza de Clara de Ovo com Recheio de Frango Desfiado, Queijo, Tomate e Manjericão
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Pizza de Clara de Ovo com Recheio de Frango Desfiado, Queijo, Tomate e Manjericão',
    'Pizza proteica e low carb',
    'Jantar',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
    25,
    180,
    2,
    'Fácil',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '4 claras de ovo',
        '1/2 xícara de frango desfiado',
        '1/4 xícara de queijo muçarela light ralado',
        '2 tomates cortados em rodelas',
        'Folhas de manjericão fresco',
        'Sal e pimenta a gosto',
        'Azeite para untar'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C.',
        'Bata as claras de ovo com sal e pimenta até ficarem firmes.',
        'Em uma frigideira antiaderente untada com azeite, despeje as claras batidas e deixe dourar como uma base de pizza.',
        'Após dourar, cubra a base com o frango desfiado, o queijo, os tomates e o manjericão.',
        'Leve ao forno por 5-7 minutos até o queijo derreter. Sirva imediatamente.'
    ],
    'Pizza sem culpa para o jantar!',
    ARRAY['low carb', 'proteico', 'pizza fit'],
    '{"Proteínas": "25g", "Carboidratos": "5g", "Gorduras": "8g", "Fibras": "1g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Low Carb']
);

-- Receita 55: Queijo de Castanhas
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Queijo de Castanhas',
    'Queijo vegano cremoso',
    'Acompanhamentos',
    'https://images.unsplash.com/photo-1626200419199-391ae4be7a41',
    15,
    160,
    6,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de castanha de caju crua (deixe de molho por 4 horas)',
        '1/4 xícara de água',
        '2 colheres de sopa de levedura nutricional',
        '1 colher de sopa de suco de limão',
        '1 dente de alho',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Escorra as castanhas de caju e coloque no processador de alimentos.',
        'Adicione a água, a levedura nutricional, o suco de limão, o alho, o sal e a pimenta.',
        'Processe até obter uma consistência cremosa e homogênea.',
        'Transfira para um recipiente e leve à geladeira por pelo menos 4 horas para firmar.',
        'Sirva como patê ou acompanhando pães integrais.'
    ],
    'Rico em proteínas vegetais e gorduras boas!',
    ARRAY['vegano', 'queijo vegetal', 'castanhas'],
    '{"Proteínas": "6g", "Carboidratos": "8g", "Gorduras": "12g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas', 'Gorduras'],
    ARRAY['Vegano']
);

-- Receita 56: Quiche de Alho-Poró e Tofu
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Quiche de Alho-Poró e Tofu',
    'Quiche vegana e nutritiva',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
    40,
    180,
    6,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 alho-poró cortado em rodelas finas',
        '200g de tofu firme',
        '1/2 xícara de farinha de grão de bico',
        '1/4 xícara de leite de amêndoas',
        '1 colher de chá de cúrcuma',
        '1 colher de sopa de azeite de oliva',
        'Sal e pimenta a gosto',
        'Massa pronta de torta vegana (opcional)'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C.',
        'Refogue o alho-poró no azeite até ficar macio.',
        'Em um processador de alimentos, bata o tofu, a farinha de grão de bico, o leite de amêndoas, a cúrcuma, o sal e a pimenta até ficar uma mistura cremosa.',
        'Acrescente o alho-poró refogado e misture bem.',
        'Se desejar, coloque a mistura em uma forma de torta com massa pronta.',
        'Leve ao forno por 25-30 minutos ou até a superfície dourar.'
    ],
    'Rica em proteínas vegetais!',
    ARRAY['vegano', 'quiche', 'alho-poró'],
    '{"Proteínas": "10g", "Carboidratos": "15g", "Gorduras": "8g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano', 'Low Carb']
);

-- Receita 57: Quiche Funcional
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Quiche Funcional',
    'Quiche nutritiva e equilibrada',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
    40,
    220,
    6,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '3 ovos',
        '1/2 xícara de creme de leite light',
        '1/2 xícara de espinafre cozido',
        '1/2 xícara de queijo muçarela light ralado',
        '1/4 xícara de farinha de amêndoas',
        '1 colher de chá de cúrcuma',
        'Sal e pimenta a gosto',
        'Massa integral (opcional)'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C.',
        'Bata os ovos com o creme de leite e a cúrcuma até misturar bem.',
        'Adicione o espinafre cozido, o queijo, a farinha de amêndoas, o sal e a pimenta.',
        'Coloque a mistura em uma forma de torta com massa integral (se desejar).',
        'Asse por 25-30 minutos ou até dourar e ficar firme.'
    ],
    'Refeição completa e balanceada!',
    ARRAY['funcional', 'quiche', 'equilibrada'],
    '{"Proteínas": "15g", "Carboidratos": "10g", "Gorduras": "12g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Funcional', 'Low Carb']
);

-- Receita 58: Ragu de Cogumelos
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Ragu de Cogumelos',
    'Molho rico e saboroso',
    'Molhos',
    'https://images.unsplash.com/photo-1626200419199-391ae4be7a41',
    25,
    150,
    4,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '300g de cogumelos (shiitake, champignon ou o de sua preferência)',
        '1 cebola picada',
        '2 dentes de alho picados',
        '2 colheres de sopa de azeite de oliva',
        '1/2 xícara de molho de tomate natural',
        '1 colher de sopa de molho shoyu (opcional)',
        'Sal e pimenta a gosto',
        'Salsinha picada para decorar'
    ],
    ARRAY[
        'Em uma frigideira, refogue a cebola e o alho no azeite até ficarem dourados.',
        'Acrescente os cogumelos e refogue por mais 5 minutos.',
        'Adicione o molho de tomate e o molho shoyu, misture bem e cozinhe por mais 10 minutos em fogo baixo.',
        'Tempere com sal e pimenta a gosto.',
        'Decore com salsinha e sirva quente, acompanhado de arroz integral ou vegetais assados.'
    ],
    'Rico em umami e antioxidantes!',
    ARRAY['vegano', 'cogumelos', 'molho'],
    '{"Proteínas": "5g", "Carboidratos": "12g", "Gorduras": "8g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Vegano', 'Low Carb']
);

-- Receita 59: Ravioli de Abobrinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Ravioli de Abobrinha',
    'Ravioli low carb e criativo',
    'Almoço',
    'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9',
    30,
    90,
    2,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '1 abobrinha média cortada em fatias finas (como lâminas de ravioli)',
        '1/2 xícara de ricota vegana ou queijo cottage',
        '1 dente de alho picado',
        '1 colher de chá de azeite de oliva',
        'Sal e pimenta a gosto',
        'Molho de tomate fresco ou pesto para acompanhar'
    ],
    ARRAY[
        'Corte a abobrinha em lâminas finas no sentido do comprimento.',
        'Em uma frigideira, refogue o alho no azeite até dourar, adicione a ricota (ou queijo cottage) e misture bem.',
        'Coloque uma colher de sopa do recheio de ricota entre duas lâminas de abobrinha, formando os raviolis.',
        'Cozinhe os raviolis em água fervente por 3-4 minutos.',
        'Sirva com molho de tomate fresco ou pesto.'
    ],
    'Massa de vegetais é sempre uma boa opção!',
    ARRAY['low carb', 'criativo', 'ravioli'],
    '{"Proteínas": "8g", "Carboidratos": "8g", "Gorduras": "4g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Low Carb', 'Vegano']
);

-- Receita 60: Risoto de Quinoa, Shitake e Limão Siciliano
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Risoto de Quinoa, Shitake e Limão Siciliano',
    'Risoto sofisticado e nutritivo',
    'Almoço',
    'https://images.unsplash.com/photo-1609501676725-7186f017a4b7',
    30,
    200,
    4,
    'Médio',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '1 xícara de quinoa',
        '200g de cogumelos shitake fatiados',
        '1/2 cebola picada',
        '2 colheres de sopa de azeite de oliva',
        '1 colher de sopa de suco de limão siciliano',
        '1/4 xícara de caldo de legumes (caseiro ou sem sódio)',
        'Sal e pimenta a gosto',
        'Raspas de limão siciliano para decorar'
    ],
    ARRAY[
        'Em uma frigideira, refogue a cebola no azeite até dourar.',
        'Adicione os cogumelos e refogue por 5 minutos.',
        'Acrescente a quinoa e misture bem.',
        'Adicione o caldo de legumes, o suco de limão e cozinhe por 15 minutos até a quinoa ficar macia e o líquido ser absorvido.',
        'Tempere com sal, pimenta e raspas de limão. Sirva quente.'
    ],
    'Prato completo e sofisticado!',
    ARRAY['sofisticado', 'quinoa', 'cogumelos'],
    '{"Proteínas": "8g", "Carboidratos": "30g", "Gorduras": "8g", "Fibras": "5g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Low Carb', 'Vegetariano']
); 