-- Inserir receitas da Bruna Braga Nutrição + RayClub

-- Receita 1: Bolo de Banana de Caneca
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Bolo de Banana de Caneca',
    'Receita rápida e saudável para um lanche nutritivo',
    'Lanches',
    'https://images.unsplash.com/photo-1558303420-f814d8a590f5',
    5,
    200,
    1,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 banana madura',
        '1 ovo',
        '2 colheres de sopa de aveia',
        '1 colher de chá de fermento em pó',
        '1 colher de sopa de mel'
    ],
    ARRAY[
        'Amasse a banana e misture com o ovo, aveia, fermento e mel.',
        'Coloque em uma caneca e leve ao micro-ondas por 2-3 minutos.'
    ],
    'Adicione canela em pó para dar mais sabor e benefícios antioxidantes!',
    ARRAY['rápido', 'micro-ondas', 'lanche saudável'],
    '{"Proteínas": "8g", "Carboidratos": "35g", "Gorduras": "5g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 2: Banana Toast
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Banana Toast',
    'Toast nutritivo com banana e queijo derretido',
    'Lanches',
    'https://images.unsplash.com/photo-1528735602780-2552fd46c7af',
    10,
    250,
    1,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 banana fatiada',
        '1 colher de chá de mel',
        '1 fatia de pão de forma integral',
        '2 fatias de queijo'
    ],
    ARRAY[
        'Coloque o pão de forma na airfryer e toste por 4 minutos a 180°C.',
        'Coloque as fatias de banana sobre o pão, adicione o queijo por cima e regue com mel.',
        'Volte para a airfryer por 2 minutos até o queijo derreter.'
    ],
    'Use queijo cottage para aumentar o teor de proteínas!',
    ARRAY['airfryer', 'rápido', 'nutritivo'],
    '{"Proteínas": "10g", "Carboidratos": "40g", "Gorduras": "8g", "Fibras": "5g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 3: Gororoba de Banana
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Gororoba de Banana',
    'Mistura proteica com banana e ovos',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1525351484163-7529414344d8',
    10,
    300,
    1,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 banana madura',
        '2 ovos',
        '2 colheres de sopa de farelo de aveia',
        '50g de queijo branco'
    ],
    ARRAY[
        'Em uma frigideira, bata os ovos e acrescente os ingredientes restantes.',
        'Cozinhe mexendo até os ovos ficarem bem misturados e o queijo derreter.'
    ],
    'Perfeito para um café da manhã rico em proteínas!',
    ARRAY['proteína', 'café da manhã', 'rápido'],
    '{"Proteínas": "20g", "Carboidratos": "30g", "Gorduras": "12g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 4: Pão de Queijo de Airfryer
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Pão de Queijo de Airfryer',
    'Pão de queijo fit e proteico',
    'Lanches',
    'https://images.unsplash.com/photo-1598142982901-df6cec10ae35',
    15,
    180,
    4,
    'Fácil',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '1 xícara de polvilho doce',
        '1/2 xícara de queijo cottage',
        '1 ovo inteiro',
        '2 claras de ovo'
    ],
    ARRAY[
        'Misture todos os ingredientes até formar uma massa homogênea.',
        'Modele bolinhas e coloque na cesta da airfryer.',
        'Cozinhe a 180°C por 10 minutos ou até dourar.'
    ],
    'Ótima opção para quem busca reduzir calorias sem abrir mão do sabor!',
    ARRAY['airfryer', 'proteico', 'sem glúten'],
    '{"Proteínas": "8g", "Carboidratos": "20g", "Gorduras": "6g", "Fibras": "1g"}'::jsonb,
    ARRAY['Emagrecimento', 'Hipertrofia'],
    ARRAY['Salgado'],
    ARRAY['Café da Manhã'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 5: Tortinha de Frango de Airfryer
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Tortinha de Frango de Airfryer',
    'Tortinha proteica e saborosa',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
    25,
    250,
    2,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '200g de peito de frango desfiado',
        '1 ovo',
        '1/4 xícara de queijo ralado',
        '1 batata doce cozida'
    ],
    ARRAY[
        'Misture o frango, ovo, queijo e batata amassada.',
        'Modele em pequenas tortas e coloque na airfryer por 15 minutos a 180°C.'
    ],
    'Adicione temperos naturais como orégano e alecrim para mais sabor!',
    ARRAY['airfryer', 'proteico', 'refeição'],
    '{"Proteínas": "25g", "Carboidratos": "20g", "Gorduras": "10g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento', 'Hipertrofia'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 6: Bolo Alagado
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Bolo Alagado',
    'Bolo proteico com whey e chocolate',
    'Sobremesas',
    'https://images.unsplash.com/photo-1578985545062-69928b1d9587',
    30,
    250,
    6,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 ovos',
        '1 scoop de whey protein (sabor chocolate)',
        '1 colher de sopa de cacau em pó',
        '1 quadrado de chocolate amargo 70% cacau'
    ],
    ARRAY[
        'Misture os ovos com o whey e o cacau até formar uma massa homogênea.',
        'Coloque em uma forma untada e adicione o pedaço de chocolate por cima.',
        'Asse a 180°C por 25 minutos.'
    ],
    'O chocolate derretido no centro torna o bolo ainda mais especial!',
    ARRAY['proteico', 'sobremesa', 'whey'],
    '{"Proteínas": "10g", "Carboidratos": "15g", "Gorduras": "8g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 7: Panqueca de Espinafre e Atum
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Panqueca de Espinafre e Atum',
    'Panqueca proteica e nutritiva',
    'Almoço',
    'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445',
    15,
    220,
    2,
    'Fácil',
    4.6,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 ovos',
        '1/2 xícara de espinafre refogado',
        '1 lata de atum em água',
        '1 colher de sopa de farinha de aveia'
    ],
    ARRAY[
        'Misture todos os ingredientes e cozinhe em uma frigideira antiaderente até dourar dos dois lados.'
    ],
    'Rica em ômega-3 e ferro, perfeita para o almoço!',
    ARRAY['proteico', 'low carb', 'refeição'],
    '{"Proteínas": "28g", "Carboidratos": "10g", "Gorduras": "8g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 8: Smoothie de Frutas Vermelhas e Whey Protein
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Smoothie de Frutas Vermelhas e Whey Protein',
    'Bebida proteica pós-treino',
    'Bebidas',
    'https://images.unsplash.com/photo-1553530666-ba11a90bb0b1',
    5,
    200,
    1,
    'Fácil',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '1/2 xícara de frutas vermelhas congeladas',
        '1 scoop de whey protein (sabor baunilha)',
        '1/2 xícara de leite de amêndoas'
    ],
    ARRAY[
        'Bata todos os ingredientes no liquidificador até ficar homogêneo.'
    ],
    'Ideal para consumir até 30 minutos após o treino!',
    ARRAY['pós-treino', 'proteico', 'shake'],
    '{"Proteínas": "25g", "Carboidratos": "15g", "Gorduras": "3g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY['Pós treino'],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 9: Abobrinha Recheada com Frango e Creme de Ricota
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Abobrinha Recheada com Frango e Creme de Ricota',
    'Prato principal low carb e proteico',
    'Almoço',
    'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c',
    30,
    280,
    2,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 abobrinhas médias',
        '200g de peito de frango desfiado',
        '3 colheres de sopa de creme de ricota',
        '1 colher de sopa de azeite'
    ],
    ARRAY[
        'Corte as abobrinhas ao meio e retire o miolo.',
        'Misture o frango, creme de ricota e azeite.',
        'Recheie as abobrinhas e asse a 180°C por 20 minutos.'
    ],
    'Excelente opção low carb para o jantar!',
    ARRAY['low carb', 'proteico', 'refeição'],
    '{"Proteínas": "30g", "Carboidratos": "8g", "Gorduras": "15g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento', 'Hipertrofia'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 10: Aveioca
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Aveioca',
    'Tapioca funcional com aveia',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1528735602780-2552fd46c7af',
    10,
    180,
    1,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 ovo',
        '2 colheres de sopa de aveia',
        '2 colheres de sopa de tapioca',
        '2 fatias de queijo'
    ],
    ARRAY[
        'Misture todos os ingredientes e cozinhe em uma frigideira até dourar dos dois lados.',
        'Recheie com queijo e dobre a aveioca ao meio.'
    ],
    'Versão mais nutritiva da tapioca tradicional!',
    ARRAY['café da manhã', 'funcional', 'rápido'],
    '{"Proteínas": "12g", "Carboidratos": "22g", "Gorduras": "6g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento', 'Hipertrofia'],
    ARRAY['Salgado'],
    ARRAY['Café da Manhã'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 11: Barrinha de Proteína Artesanal
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Barrinha de Proteína Artesanal',
    'Barrinha proteica caseira para lanches',
    'Lanches',
    'https://images.unsplash.com/photo-1558985212-92c2ff0b56e7',
    20,
    150,
    6,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de aveia',
        '1 scoop de whey protein (sabor baunilha)',
        '1/2 xícara de pasta de amendoim',
        '2 colheres de sopa de mel',
        '1/4 xícara de leite de amêndoas'
    ],
    ARRAY[
        'Misture todos os ingredientes até formar uma massa homogênea.',
        'Modele em formato de barrinhas e coloque em uma assadeira forrada com papel manteiga.',
        'Deixe na geladeira por 2 horas antes de cortar em porções.'
    ],
    'Perfeita para levar na bolsa e consumir entre as refeições!',
    ARRAY['proteico', 'lanche', 'pré-treino'],
    '{"Proteínas": "10g", "Carboidratos": "18g", "Gorduras": "6g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY['Pós treino'],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 12: Beijinho Saudável
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Beijinho Saudável',
    'Doce fit sem açúcar refinado',
    'Sobremesas',
    'https://images.unsplash.com/photo-1548848221-0c2e497ed557',
    15,
    80,
    10,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de coco ralado sem açúcar',
        '1 colher de sopa de mel',
        '1 colher de sopa de leite de coco',
        '1 colher de chá de essência de baunilha'
    ],
    ARRAY[
        'Misture todos os ingredientes até formar uma massa homogênea.',
        'Modele pequenas bolinhas e passe em coco ralado.',
        'Deixe na geladeira por 1 hora para firmar.'
    ],
    'Doce saudável para matar a vontade sem sair da dieta!',
    ARRAY['doce fit', 'sobremesa', 'sem açúcar'],
    '{"Proteínas": "2g", "Carboidratos": "8g", "Gorduras": "5g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Gorduras'],
    ARRAY[]::TEXT[]
);

-- Receita 13: Berinjela Recheada
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Berinjela Recheada',
    'Prato principal vegetariano e nutritivo',
    'Almoço',
    'https://images.unsplash.com/photo-1604909052743-94e838986d24',
    30,
    250,
    2,
    'Médio',
    4.6,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 berinjelas médias',
        '200g de carne moída magra',
        '1/2 cebola picada',
        '1 tomate picado',
        '1 colher de sopa de azeite'
    ],
    ARRAY[
        'Corte as berinjelas ao meio e retire o miolo.',
        'Refogue a cebola no azeite, adicione a carne e o tomate até dourar.',
        'Recheie as berinjelas e asse a 180°C por 20 minutos.'
    ],
    'Rica em fibras e antioxidantes!',
    ARRAY['low carb', 'refeição', 'vegetais'],
    '{"Proteínas": "22g", "Carboidratos": "15g", "Gorduras": "12g", "Fibras": "6g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 14: Biscoito de Banana com Passas
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Biscoito de Banana com Passas',
    'Biscoito saudável sem farinha',
    'Lanches',
    'https://images.unsplash.com/photo-1558961363-fa8fdf82db35',
    15,
    120,
    12,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 bananas maduras amassadas',
        '1 xícara de aveia',
        '1/4 xícara de passas',
        '1 colher de chá de canela'
    ],
    ARRAY[
        'Misture todos os ingredientes até formar uma massa.',
        'Modele os biscoitos em uma assadeira forrada com papel manteiga.',
        'Asse a 180°C por 10-12 minutos até dourar.'
    ],
    'Ótimo para levar como lanche na escola ou trabalho!',
    ARRAY['sem farinha', 'lanche', 'biscoito fit'],
    '{"Proteínas": "3g", "Carboidratos": "22g", "Gorduras": "2g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 15: Bolinho de Prestígio
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Bolinho de Prestígio',
    'Versão fit do clássico bolinho',
    'Sobremesas',
    'https://images.unsplash.com/photo-1587668178277-295251f900ce',
    25,
    150,
    8,
    'Médio',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '1 xícara de coco ralado sem açúcar',
        '1 scoop de whey protein (sabor chocolate)',
        '2 colheres de sopa de cacau em pó',
        '1 colher de sopa de mel',
        '1/4 xícara de leite de amêndoas'
    ],
    ARRAY[
        'Misture todos os ingredientes até formar uma massa homogênea.',
        'Modele em bolinhos e coloque em uma assadeira forrada com papel manteiga.',
        'Asse a 180°C por 15 minutos.'
    ],
    'Sabor de infância em versão saudável!',
    ARRAY['proteico', 'chocolate', 'sobremesa fit'],
    '{"Proteínas": "8g", "Carboidratos": "12g", "Gorduras": "7g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 16: Bolo de Maçã com Canela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Bolo de Maçã com Canela',
    'Bolo aromático e saudável',
    'Sobremesas',
    'https://images.unsplash.com/photo-1562440499-64c9a111f713',
    40,
    180,
    8,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 maçãs picadas',
        '2 ovos',
        '1/2 xícara de farinha de aveia',
        '1 colher de chá de canela',
        '1/4 xícara de mel'
    ],
    ARRAY[
        'Misture todos os ingredientes em uma tigela até formar uma massa homogênea.',
        'Despeje em uma forma untada e asse a 180°C por 30-35 minutos até dourar.'
    ],
    'A canela ajuda a controlar os níveis de açúcar no sangue!',
    ARRAY['bolo fit', 'maçã', 'canela'],
    '{"Proteínas": "5g", "Carboidratos": "28g", "Gorduras": "5g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 17: Bolo de Laranja com Casca
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Bolo de Laranja com Casca',
    'Bolo nutritivo aproveitando a laranja inteira',
    'Sobremesas',
    'https://images.unsplash.com/photo-1563805042-7684c019e1cb',
    30,
    200,
    8,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 laranjas médias (com casca)',
        '2 ovos',
        '1 xícara de farinha de aveia',
        '1 colher de chá de fermento em pó',
        '1/4 xícara de mel'
    ],
    ARRAY[
        'Bata as laranjas com casca no liquidificador até obter um suco espesso.',
        'Misture com os ovos, farinha, fermento e mel.',
        'Asse a 180°C por 30 minutos até dourar.'
    ],
    'A casca da laranja é rica em fibras e vitamina C!',
    ARRAY['bolo integral', 'laranja', 'aproveitamento total'],
    '{"Proteínas": "6g", "Carboidratos": "32g", "Gorduras": "4g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 18: Caldo Verde
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Caldo Verde',
    'Sopa nutritiva e reconfortante',
    'Sopas',
    'https://images.unsplash.com/photo-1547592166-23ac45744acd',
    30,
    150,
    4,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '300g de batata doce',
        '200g de couve manteiga',
        '1 litro de caldo de legumes',
        '1 dente de alho picado',
        '1 colher de sopa de azeite'
    ],
    ARRAY[
        'Cozinhe a batata doce até amolecer.',
        'Refogue o alho no azeite e adicione o caldo de legumes.',
        'Bata a batata e adicione à sopa.',
        'Cozinhe por 10 minutos e adicione a couve picada.'
    ],
    'Perfeita para os dias frios e para aumentar a imunidade!',
    ARRAY['sopa', 'vegetal', 'comfort food'],
    '{"Proteínas": "4g", "Carboidratos": "25g", "Gorduras": "4g", "Fibras": "5g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 19: Caldo de Abóbora
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Caldo de Abóbora',
    'Sopa cremosa e nutritiva',
    'Sopas',
    'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a',
    30,
    180,
    4,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '500g de abóbora',
        '1 litro de caldo de legumes',
        '1 cebola picada',
        '1 colher de sopa de azeite'
    ],
    ARRAY[
        'Cozinhe a abóbora até amolecer.',
        'Refogue a cebola no azeite e adicione o caldo de legumes.',
        'Bata a abóbora e adicione à sopa.',
        'Cozinhe por 10 minutos.'
    ],
    'Rica em vitamina A e betacaroteno!',
    ARRAY['sopa', 'abóbora', 'cremoso'],
    '{"Proteínas": "3g", "Carboidratos": "30g", "Gorduras": "5g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 20: Caldo de Legumes
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Caldo de Legumes',
    'Sopa leve e nutritiva',
    'Sopas',
    'https://images.unsplash.com/photo-1547592166-23ac45744acd',
    30,
    120,
    4,
    'Fácil',
    4.6,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 cenoura',
        '1 batata',
        '1 cebola',
        '1 litro de caldo de legumes',
        '1 colher de sopa de azeite'
    ],
    ARRAY[
        'Corte os legumes em cubos e cozinhe no caldo de legumes até amolecerem.',
        'Bata tudo no liquidificador e ajuste o tempero.'
    ],
    'Ótima para desintoxicar o organismo!',
    ARRAY['sopa', 'detox', 'legumes'],
    '{"Proteínas": "3g", "Carboidratos": "20g", "Gorduras": "3g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Detox']::TEXT[]
);

-- Continuar com as próximas receitas... 