-- Continuação das receitas da Bruna Braga Nutrição + RayClub

-- Receita 21: Canja de Galinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Canja de Galinha',
    'Sopa nutritiva e reconfortante',
    'Sopas',
    'https://images.unsplash.com/photo-1574653853027-5382a3d23a15',
    40,
    200,
    4,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '200g de peito de frango desfiado',
        '1 cenoura picada',
        '1 xícara de arroz',
        '1 litro de caldo de galinha',
        '1 colher de sopa de azeite'
    ],
    ARRAY[
        'Cozinhe o arroz e a cenoura no caldo de galinha até ficarem macios.',
        'Adicione o frango desfiado e deixe cozinhar por 10 minutos.'
    ],
    'Perfeita para fortalecer o sistema imunológico!',
    ARRAY['sopa', 'proteico', 'comfort food'],
    '{"Proteínas": "18g", "Carboidratos": "22g", "Gorduras": "6g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 22: Caponata de Berinjela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Caponata de Berinjela',
    'Antepasto italiano saudável',
    'Acompanhamentos',
    'https://images.unsplash.com/photo-1609501676725-7186f017a4b7',
    40,
    150,
    4,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 berinjelas médias picadas',
        '1 pimentão vermelho picado',
        '1 cebola roxa picada',
        '2 tomates picados',
        '2 colheres de sopa de azeite',
        '1 colher de sopa de vinagre balsâmico',
        '1 colher de chá de açúcar mascavo',
        '1 colher de chá de orégano',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Aqueça o azeite em uma panela grande e refogue a cebola até dourar.',
        'Adicione as berinjelas, pimentão e tomates, cozinhando por 10 minutos.',
        'Junte o vinagre balsâmico, o açúcar mascavo, orégano, sal e pimenta.',
        'Cozinhe por mais 10 minutos até os legumes ficarem macios e o líquido reduzir.',
        'Sirva quente ou morno como acompanhamento ou entrada.'
    ],
    'Rica em antioxidantes e fibras!',
    ARRAY['vegano', 'mediterrâneo', 'antepasto'],
    '{"Proteínas": "3g", "Carboidratos": "18g", "Gorduras": "8g", "Fibras": "6g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Vegano']::TEXT[]
);

-- Receita 23: Chips de Batata Doce
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Chips de Batata Doce',
    'Snack crocante e saudável',
    'Lanches',
    'https://images.unsplash.com/photo-1598103442097-8b74394b95c6',
    30,
    120,
    4,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '2 batatas doces médias',
        '1 colher de sopa de azeite',
        '1 colher de chá de sal',
        '1/2 colher de chá de pimenta-do-reino',
        '1/2 colher de chá de páprica (opcional)'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C e forre uma assadeira com papel manteiga.',
        'Lave bem as batatas e corte-as em fatias finas.',
        'Em uma tigela, misture as batatas com azeite, sal, pimenta e páprica.',
        'Disponha as fatias de batata na assadeira, sem sobrepor, e asse por 20-25 minutos, virando as chips na metade do tempo.',
        'Deixe esfriar antes de servir.'
    ],
    'Substituto perfeito para chips industrializados!',
    ARRAY['snack', 'vegano', 'crocante'],
    '{"Proteínas": "2g", "Carboidratos": "22g", "Gorduras": "3g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Vegano']::TEXT[]
);

-- Receita 24: Snacks de Grão de Bico
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Snacks de Grão de Bico',
    'Petisco proteico e crocante',
    'Lanches',
    'https://images.unsplash.com/photo-1585238342024-78d387f4a707',
    40,
    140,
    4,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de grão de bico cozido',
        '1 colher de sopa de azeite',
        '1 colher de chá de cúrcuma',
        '1 colher de chá de cominho',
        '1/2 colher de chá de pimenta caiena (opcional)',
        'Sal a gosto'
    ],
    ARRAY[
        'Preaqueça o forno a 200°C e forre uma assadeira com papel manteiga.',
        'Misture o grão de bico cozido com azeite, cúrcuma, cominho, pimenta caiena e sal.',
        'Espalhe o grão de bico na assadeira em uma única camada.',
        'Asse por 30-40 minutos, mexendo a cada 10 minutos até que os grãos fiquem crocantes.',
        'Deixe esfriar e sirva como lanche.'
    ],
    'Rico em proteínas vegetais e fibras!',
    ARRAY['proteico', 'vegano', 'snack'],
    '{"Proteínas": "6g", "Carboidratos": "18g", "Gorduras": "4g", "Fibras": "5g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano']::TEXT[]
);

-- Receita 25: Coxinha Funcional de Frango com Creme de Queijo Cottage
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Coxinha Funcional de Frango com Creme de Queijo Cottage',
    'Versão saudável da coxinha tradicional',
    'Lanches',
    'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0',
    60,
    180,
    8,
    'Médio',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '300g de peito de frango cozido e desfiado',
        '1/2 xícara de queijo cottage',
        '1/4 xícara de aveia em flocos finos',
        '1 colher de sopa de azeite',
        '1/2 cebola picada',
        '1 dente de alho picado',
        'Sal e pimenta a gosto',
        'Farinha de arroz para empanar',
        '1 ovo para empanar'
    ],
    ARRAY[
        'Refogue a cebola e o alho no azeite até dourarem.',
        'Adicione o frango desfiado, o queijo cottage e misture bem.',
        'Adicione a aveia e tempere com sal e pimenta.',
        'Modele a massa em formato de coxinha.',
        'Passe as coxinhas na farinha de arroz e no ovo batido.',
        'Asse a 180°C por 25-30 minutos, até ficarem douradas.'
    ],
    'Perfeita para festas saudáveis!',
    ARRAY['funcional', 'proteico', 'festa'],
    '{"Proteínas": "15g", "Carboidratos": "12g", "Gorduras": "8g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Funcional']::TEXT[]
);

-- Receita 26: Crepe de Beterraba
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Crepe de Beterraba',
    'Crepe colorido e nutritivo',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
    25,
    140,
    2,
    'Fácil',
    4.6,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 beterraba pequena ralada',
        '1/2 xícara de farinha de grão-de-bico',
        '1/4 xícara de água',
        '1 colher de sopa de azeite',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Misture a beterraba ralada, farinha de grão-de-bico, água, azeite, sal e pimenta.',
        'Aqueça uma frigideira antiaderente e despeje a mistura, espalhando para formar um crepe fino.',
        'Cozinhe por 2-3 minutos de cada lado até dourar.',
        'Sirva com o recheio de sua preferência (ex: legumes grelhados).'
    ],
    'Rica em ferro e antioxidantes!',
    ARRAY['vegano', 'colorido', 'sem glúten'],
    '{"Proteínas": "6g", "Carboidratos": "18g", "Gorduras": "5g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Vegano']::TEXT[]
);

-- Receita 27: Espaguete de Abobrinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Espaguete de Abobrinha',
    'Alternativa low carb para massas',
    'Almoço',
    'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
    15,
    100,
    2,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '2 abobrinhas médias',
        '1 colher de sopa de azeite',
        '1 dente de alho picado',
        '1/2 xícara de molho de tomate natural',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Use um espiralizador para fazer o espaguete de abobrinha.',
        'Aqueça o azeite em uma frigideira e refogue o alho até dourar.',
        'Adicione o espaguete de abobrinha e refogue por 2-3 minutos.',
        'Adicione o molho de tomate, sal e pimenta e cozinhe por mais 2 minutos.',
        'Sirva como acompanhamento ou prato principal.'
    ],
    'Perfeito para reduzir carboidratos sem perder sabor!',
    ARRAY['low carb', 'vegano', 'leve'],
    '{"Proteínas": "3g", "Carboidratos": "12g", "Gorduras": "6g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Vegano', 'Low Carb']::TEXT[]
);

-- Receita 28: Falafel de Forno
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Falafel de Forno',
    'Bolinho árabe assado e saudável',
    'Lanches',
    'https://images.unsplash.com/photo-1593001874117-c99c800e3eb6',
    40,
    150,
    12,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de grão de bico cozido',
        '1/2 cebola picada',
        '2 dentes de alho picados',
        '1 colher de chá de cominho',
        '1/2 colher de chá de coentro em pó',
        '2 colheres de sopa de azeite',
        '2 colheres de sopa de farinha de grão de bico',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'No processador de alimentos, bata o grão de bico, cebola, alho, cominho, coentro, azeite e farinha até formar uma massa.',
        'Modele em bolinhos e coloque em uma assadeira forrada com papel manteiga.',
        'Asse a 180°C por 25-30 minutos, virando os bolinhos na metade do tempo.'
    ],
    'Fonte de proteína vegetal e fibras!',
    ARRAY['vegano', 'árabe', 'proteico'],
    '{"Proteínas": "5g", "Carboidratos": "18g", "Gorduras": "5g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano']::TEXT[]
);

-- Receita 29: Frango Teriyaki com Legumes Assados
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Frango Teriyaki com Legumes Assados',
    'Prato oriental saudável e saboroso',
    'Almoço',
    'https://images.unsplash.com/photo-1609183590563-7710381094db',
    40,
    300,
    2,
    'Médio',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '2 peitos de frango',
        '1/4 xícara de molho shoyu light',
        '1 colher de sopa de mel',
        '1 colher de sopa de gengibre ralado',
        '1 cenoura cortada em tiras',
        '1 abobrinha cortada em tiras',
        '1/2 pimentão vermelho cortado em tiras',
        '1 colher de sopa de azeite'
    ],
    ARRAY[
        'Misture o molho shoyu, mel e gengibre.',
        'Marinate o frango por 20 minutos nessa mistura.',
        'Em uma assadeira, coloque os legumes, regue com azeite e asse a 200°C por 20 minutos.',
        'Enquanto isso, grelhe o frango até dourar e cozinhar completamente.',
        'Sirva o frango fatiado sobre os legumes assados.'
    ],
    'Equilibrio perfeito entre proteínas e vegetais!',
    ARRAY['oriental', 'proteico', 'colorido'],
    '{"Proteínas": "35g", "Carboidratos": "20g", "Gorduras": "10g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 30: Granola Caseira
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Granola Caseira',
    'Granola crocante e nutritiva',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38',
    30,
    180,
    8,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 xícaras de aveia em flocos',
        '1/2 xícara de nozes picadas',
        '1/2 xícara de amêndoas',
        '1/4 xícara de sementes de abóbora',
        '1/4 xícara de mel ou xarope de agave',
        '1/4 xícara de óleo de coco derretido',
        '1 colher de chá de canela em pó',
        '1/2 colher de chá de baunilha',
        '1/4 xícara de uvas passas ou cranberries secas (opcional)'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C e forre uma assadeira com papel manteiga.',
        'Misture todos os ingredientes secos em uma tigela grande.',
        'Em uma tigela pequena, misture o mel, o óleo de coco e a baunilha.',
        'Adicione os ingredientes líquidos à mistura seca e misture bem.',
        'Espalhe a mistura na assadeira de maneira uniforme e asse por 20-25 minutos, mexendo na metade do tempo, até dourar.',
        'Deixe esfriar completamente antes de armazenar em um recipiente hermético.'
    ],
    'Perfeita com iogurte e frutas frescas!',
    ARRAY['café da manhã', 'crocante', 'energético'],
    '{"Proteínas": "6g", "Carboidratos": "25g", "Gorduras": "10g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
); 