-- Continuação das receitas da Bruna Braga Nutrição + RayClub (Parte 4)

-- Receita 41: Nhoque de Cenoura
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Nhoque de Cenoura',
    'Nhoque colorido e nutritivo',
    'Almoço',
    'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9',
    40,
    120,
    4,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 cenouras médias cozidas e amassadas',
        '1 xícara de farinha de arroz',
        '1/4 xícara de amido de batata-doce',
        '1 ovo',
        'Sal e pimenta a gosto',
        'Água (se necessário para ajustar a consistência)'
    ],
    ARRAY[
        'Cozinhe as cenouras até ficarem macias, depois amasse bem.',
        'Em uma tigela, combine a cenoura amassada, a farinha de arroz, o amido de batata-doce, o ovo, o sal e a pimenta.',
        'Misture até formar uma massa homogênea. Se necessário, adicione um pouco de água para dar a consistência ideal.',
        'Modele os nhoques e cozinhe-os em água fervente com sal. Quando subirem à superfície, estão prontos.',
        'Sirva com molho de sua preferência.'
    ],
    'Rico em betacaroteno e vitamina A!',
    ARRAY['vegetal', 'colorido', 'nhoque'],
    '{"Proteínas": "4g", "Carboidratos": "22g", "Gorduras": "2g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Low Carb']
);

-- Receita 42: Nhoque de Mandioquinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Nhoque de Mandioquinha',
    'Nhoque macio e saboroso',
    'Almoço',
    'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9',
    40,
    130,
    4,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 mandioquinhas médias cozidas e amassadas',
        '1/2 xícara de farinha de arroz',
        '1 ovo',
        '1 colher de sopa de azeite de oliva',
        'Sal e pimenta a gosto',
        'Água (se necessário para ajustar a consistência)'
    ],
    ARRAY[
        'Cozinhe as mandioquinhas até ficarem macias, depois amasse bem.',
        'Em uma tigela, combine a mandioquinha amassada, a farinha de arroz, o ovo, o azeite, o sal e a pimenta.',
        'Misture até formar uma massa homogênea e, se necessário, adicione um pouco de água para dar a consistência ideal.',
        'Modele os nhoques e cozinhe-os em água fervente com sal. Quando subirem à superfície, estão prontos.',
        'Sirva com molho de sua preferência.'
    ],
    'Fonte de energia e fibras!',
    ARRAY['vegetal', 'tradicional', 'nhoque'],
    '{"Proteínas": "3g", "Carboidratos": "25g", "Gorduras": "3g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Low Carb']
);

-- Receita 43: Nuggets de Frango Funcional
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Nuggets de Frango Funcional',
    'Nuggets crocantes e saudáveis',
    'Lanches',
    'https://images.unsplash.com/photo-1562967914-608f82629710',
    30,
    180,
    4,
    'Fácil',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '300g de peito de frango moído',
        '1 ovo',
        '1/2 xícara de farelo de aveia',
        '2 colheres de sopa de queijo parmesão ralado',
        '1 colher de chá de alho em pó',
        'Sal e pimenta a gosto',
        'Azeite para untar'
    ],
    ARRAY[
        'Em uma tigela, misture o frango moído, o ovo, o farelo de aveia, o queijo parmesão, o alho, o sal e a pimenta.',
        'Modele a mistura em pequenos pedaços no formato de nuggets.',
        'Coloque-os em uma assadeira untada com azeite e asse a 180°C por cerca de 20-25 minutos, virando-os na metade do tempo para dourar por igual.',
        'Sirva quente, acompanhado de molho de sua preferência.'
    ],
    'Perfeito para as crianças!',
    ARRAY['proteico', 'crocante', 'infantil'],
    '{"Proteínas": "20g", "Carboidratos": "10g", "Gorduras": "8g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento', 'Hipertrofia'],
    ARRAY['Salgado', 'Paladar Infantil'],
    ARRAY['Lanche da Tarde', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Funcional']
);

-- Receita 44: Omelete de Forno
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Omelete de Forno',
    'Omelete prático e nutritivo',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1525351484163-7529414344d8',
    25,
    150,
    4,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '4 ovos',
        '1/2 xícara de legumes picados (como espinafre, pimentão e tomate)',
        '1/4 xícara de queijo cottage',
        'Sal e pimenta a gosto',
        'Azeite para untar'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C e unte uma assadeira com azeite.',
        'Em uma tigela, bata os ovos e misture os legumes e o queijo cottage. Tempere com sal e pimenta.',
        'Despeje a mistura na assadeira e leve ao forno por 15-20 minutos, até que esteja firme e dourado por cima.',
        'Sirva imediatamente, acompanhado de uma salada.'
    ],
    'Prepare no domingo para a semana toda!',
    ARRAY['proteico', 'meal prep', 'fácil'],
    '{"Proteínas": "12g", "Carboidratos": "5g", "Gorduras": "8g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Café da Manhã', 'Almoço'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 45: Panqueca de Cacau
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Panqueca de Cacau',
    'Panqueca de chocolate saudável',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1565299543923-37dd37887442',
    15,
    120,
    2,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 banana madura',
        '1 ovo',
        '2 colheres de sopa de cacau em pó',
        '1 colher de chá de essência de baunilha',
        '1/4 xícara de leite de amêndoas (ou outro leite vegetal)'
    ],
    ARRAY[
        'Em um liquidificador ou tigela, bata a banana, o ovo, o cacau, a essência de baunilha e o leite.',
        'Aqueça uma frigideira antiaderente e despeje pequenas porções da massa, formando as panquecas.',
        'Cozinhe por 2-3 minutos de cada lado, até dourar.',
        'Sirva com mel ou frutas frescas, se desejar.'
    ],
    'Satisfaz a vontade de doce de forma saudável!',
    ARRAY['chocolate', 'panqueca', 'café da manhã'],
    '{"Proteínas": "6g", "Carboidratos": "20g", "Gorduras": "3g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 46: Pão Caseiro sem Glúten
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Pão Caseiro sem Glúten',
    'Pão macio e nutritivo',
    'Pães',
    'https://images.unsplash.com/photo-1509440159596-0249088772ff',
    90,
    120,
    12,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 xícaras de farinha de arroz',
        '1/2 xícara de fécula de batata',
        '1 colher de sopa de fermento biológico seco',
        '1/4 xícara de azeite de oliva',
        '1 1/2 xícara de água morna',
        '1 colher de chá de sal',
        '1 colher de chá de açúcar'
    ],
    ARRAY[
        'Em uma tigela, misture a farinha de arroz, a fécula de batata, o fermento, o sal e o açúcar.',
        'Adicione o azeite e a água morna aos poucos e misture até formar uma massa homogênea.',
        'Deixe a massa descansar por 1 hora em um lugar morno.',
        'Modele a massa em forma de pão e coloque em uma assadeira untada.',
        'Leve ao forno preaquecido a 180°C por cerca de 40-45 minutos ou até dourar.'
    ],
    'Perfeito para quem tem intolerância ao glúten!',
    ARRAY['sem glúten', 'pão', 'caseiro'],
    '{"Proteínas": "3g", "Carboidratos": "22g", "Gorduras": "3g", "Fibras": "1g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Café da Manhã'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 47: Pastinha de Berinjela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Pastinha de Berinjela',
    'Pasta cremosa e saborosa',
    'Acompanhamentos',
    'https://images.unsplash.com/photo-1609501676725-7186f017a4b7',
    25,
    90,
    4,
    'Fácil',
    4.6,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 berinjela média',
        '1 colher de sopa de azeite de oliva',
        '1 dente de alho picado',
        '1 colher de sopa de suco de limão',
        'Sal e pimenta a gosto',
        'Salsinha a gosto'
    ],
    ARRAY[
        'Corte a berinjela em cubos e cozinhe-a no vapor até ficar bem macia.',
        'Em uma frigideira, refogue o alho no azeite até dourar, depois adicione a berinjela cozida e amasse-a com um garfo.',
        'Tempere com suco de limão, sal e pimenta e mexa bem.',
        'Finalize com salsinha picada e sirva como acompanhamento ou com torradas.'
    ],
    'Ótima opção de entrada saudável!',
    ARRAY['vegano', 'pasta', 'berinjela'],
    '{"Proteínas": "2g", "Carboidratos": "10g", "Gorduras": "5g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY['Vegano']
);

-- Receita 48: Patê de Frango
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Patê de Frango',
    'Patê cremoso e proteico',
    'Acompanhamentos',
    'https://images.unsplash.com/photo-1626200419199-391ae4be7a41',
    15,
    130,
    4,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '200g de peito de frango cozido e desfiado',
        '1 colher de sopa de azeite de oliva',
        '1/2 cebola picada',
        '1 colher de sopa de mostarda',
        '1 colher de sopa de requeijão light',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Em uma frigideira, refogue a cebola no azeite até dourar.',
        'Adicione o frango desfiado e misture bem.',
        'Acrescente a mostarda, o requeijão, sal e pimenta. Misture até ficar homogêneo.',
        'Transfira para um recipiente e leve à geladeira por 30 minutos antes de servir.'
    ],
    'Perfeito para sanduíches saudáveis!',
    ARRAY['proteico', 'patê', 'frango'],
    '{"Proteínas": "15g", "Carboidratos": "3g", "Gorduras": "6g", "Fibras": "1g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 49: Patê de Atum
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Patê de Atum',
    'Patê rico em ômega-3',
    'Acompanhamentos',
    'https://images.unsplash.com/photo-1626200419199-391ae4be7a41',
    10,
    100,
    4,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 lata de atum em água, escorrido',
        '2 colheres de sopa de requeijão light',
        '1 colher de sopa de suco de limão',
        '1 colher de chá de mostarda',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Em uma tigela, amasse o atum com um garfo.',
        'Adicione o requeijão, o suco de limão, a mostarda, o sal e a pimenta.',
        'Misture bem até ficar cremoso e homogêneo.',
        'Sirva com torradas ou vegetais crus.'
    ],
    'Fonte de proteína magra e ômega-3!',
    ARRAY['proteico', 'ômega-3', 'patê'],
    '{"Proteínas": "12g", "Carboidratos": "2g", "Gorduras": "4g", "Fibras": "0g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
);

-- Receita 50: Patê de Ricota com Alho
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Patê de Ricota com Alho',
    'Patê leve e aromático',
    'Acompanhamentos',
    'https://images.unsplash.com/photo-1626200419199-391ae4be7a41',
    10,
    90,
    4,
    'Fácil',
    4.6,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '200g de ricota amassada',
        '1 dente de alho picado',
        '1 colher de sopa de azeite de oliva',
        'Sal e pimenta a gosto',
        'Salsinha picada a gosto'
    ],
    ARRAY[
        'Em uma tigela, misture a ricota com o alho picado.',
        'Adicione o azeite, sal, pimenta e a salsinha.',
        'Misture bem até ficar homogêneo e sirva com biscoitos integrais ou vegetais.'
    ],
    'Opção leve para lanches!',
    ARRAY['leve', 'ricota', 'patê'],
    '{"Proteínas": "8g", "Carboidratos": "3g", "Gorduras": "5g", "Fibras": "0g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano']
); 