-- Continuação das receitas da Bruna Braga Nutrição + RayClub (Parte 3)

-- Receita 31: Gratinado Light de Frango
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Gratinado Light de Frango',
    'Prato cremoso e proteico',
    'Almoço',
    'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d',
    40,
    250,
    4,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '500g de peito de frango cozido e desfiado',
        '1/2 xícara de creme de leite light',
        '1/2 xícara de queijo parmesão ralado',
        '1/2 xícara de queijo muçarela light ralado',
        '1 cebola picada',
        '2 dentes de alho picados',
        '1 colher de sopa de azeite',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C.',
        'Refogue a cebola e o alho no azeite até dourarem.',
        'Adicione o frango desfiado e cozinhe por 5 minutos.',
        'Misture o creme de leite, o queijo parmesão e a muçarela, temperando com sal e pimenta.',
        'Transfira a mistura para um refratário, cubra com queijo e leve ao forno por 15 minutos ou até dourar.'
    ],
    'Sirva com salada verde para uma refeição completa!',
    ARRAY['proteico', 'gratinado', 'comfort food'],
    '{"Proteínas": "35g", "Carboidratos": "8g", "Gorduras": "12g", "Fibras": "1g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Funcional']
);

-- Receita 32: Grãomelete (Omelete de Grão de Bico)
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Grãomelete (Omelete de Grão de Bico)',
    'Omelete vegano rico em proteínas',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1525351484163-7529414344d8',
    15,
    180,
    2,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de farinha de grão de bico',
        '1/2 xícara de água',
        '1 colher de sopa de azeite',
        '1/2 cebola picada',
        '1 tomate picado',
        '1 colher de chá de cúrcuma',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Em uma tigela, misture a farinha de grão de bico com água até formar uma massa espessa.',
        'Aqueça o azeite em uma frigideira e refogue a cebola e o tomate até ficarem macios.',
        'Adicione a mistura de farinha de grão de bico, cúrcuma, sal e pimenta e cozinhe por 5-7 minutos de cada lado até dourar.',
        'Sirva quente com vegetais ou molho de sua preferência.'
    ],
    'Excelente fonte de proteína vegetal!',
    ARRAY['vegano', 'proteico', 'sem glúten'],
    '{"Proteínas": "12g", "Carboidratos": "20g", "Gorduras": "8g", "Fibras": "5g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano']
);

-- Receita 33: Hambúrguer Caseiro
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Hambúrguer Caseiro',
    'Hambúrguer saudável e saboroso',
    'Almoço',
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    30,
    350,
    4,
    'Médio',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '500g de carne de patinho moída',
        '1/2 cebola picada',
        '1 colher de sopa de azeite',
        '1 dente de alho picado',
        '1 ovo',
        'Sal e pimenta a gosto',
        '4 pães integrais',
        '4 fatias de queijo muçarela light',
        'Alface, tomate e cebola para o recheio'
    ],
    ARRAY[
        'Em uma tigela, misture a carne moída, cebola, alho, ovo, azeite, sal e pimenta.',
        'Modele a mistura em 4 hambúrgueres e reserve.',
        'Aqueça uma frigideira e cozinhe os hambúrgueres por 4-5 minutos de cada lado, até dourar.',
        'Monte os hambúrgueres nos pães, adicionando uma fatia de queijo e os vegetais.'
    ],
    'Use carne magra para reduzir o teor de gordura!',
    ARRAY['hambúrguer', 'proteico', 'refeição'],
    '{"Proteínas": "30g", "Carboidratos": "35g", "Gorduras": "15g", "Fibras": "5g"}'::jsonb,
    ARRAY['Emagrecimento', 'Hipertrofia'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Funcional']
);

-- Receita 34: Lasanha de Berinjela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Lasanha de Berinjela',
    'Lasanha low carb e nutritiva',
    'Almoço',
    'https://images.unsplash.com/photo-1574894709920-11b28e7367e3',
    60,
    180,
    6,
    'Médio',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 berinjelas grandes cortadas em fatias finas',
        '1 xícara de molho de tomate',
        '1/2 xícara de queijo ricota ou tofu amassado',
        '1/2 xícara de espinafre cozido',
        '1/4 xícara de queijo parmesão ralado (opcional)',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C.',
        'Grelhe as fatias de berinjela em uma frigideira com um pouco de azeite até ficarem douradas.',
        'Em uma tigela, misture o tofu ou ricota com o espinafre, sal e pimenta.',
        'Monte a lasanha em um refratário, alternando camadas de berinjela, molho de tomate e a mistura de tofu/ricota.',
        'Finalize com o queijo parmesão e leve ao forno por 30 minutos.'
    ],
    'Substitua a massa tradicional por vegetais!',
    ARRAY['low carb', 'vegetal', 'lasanha'],
    '{"Proteínas": "12g", "Carboidratos": "15g", "Gorduras": "8g", "Fibras": "6g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano']
);

-- Receita 35: Lasanha de Abobrinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Lasanha de Abobrinha',
    'Versão leve e saborosa da lasanha',
    'Almoço',
    'https://images.unsplash.com/photo-1560035285-64808ba47bda',
    60,
    160,
    6,
    'Médio',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '2 abobrinhas cortadas em fatias finas',
        '1 xícara de molho de tomate',
        '1/2 xícara de queijo ricota ou tofu amassado',
        '1/4 xícara de espinafre cozido',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C.',
        'Grelhe as fatias de abobrinha em uma frigideira com azeite até ficarem douradas.',
        'Em uma tigela, misture o tofu ou ricota com espinafre, sal e pimenta.',
        'Monte a lasanha alternando camadas de abobrinha, molho de tomate e a mistura de tofu/ricota.',
        'Leve ao forno por 30 minutos, até dourar.'
    ],
    'Perfeita para quem busca reduzir carboidratos!',
    ARRAY['low carb', 'vegetal', 'leve'],
    '{"Proteínas": "10g", "Carboidratos": "12g", "Gorduras": "7g", "Fibras": "4g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano']
);

-- Receita 36: Mexido de Tofu
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Mexido de Tofu',
    'Scramble vegano rico em proteínas',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
    15,
    180,
    2,
    'Fácil',
    4.6,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '200g de tofu firme',
        '1/2 cebola picada',
        '1 tomate picado',
        '1/2 pimentão picado',
        '1 colher de chá de cúrcuma em pó',
        '1 colher de sopa de azeite',
        '1 dente de alho picado',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Aqueça o azeite em uma frigideira e refogue a cebola, o alho e o pimentão até ficarem macios.',
        'Esfarele o tofu com as mãos e adicione à frigideira.',
        'Adicione o tomate, a cúrcuma, o sal e a pimenta e cozinhe por 5-7 minutos, mexendo ocasionalmente.',
        'Sirva quente, com uma fatia de pão integral ou salada.'
    ],
    'A cúrcuma dá cor e tem propriedades anti-inflamatórias!',
    ARRAY['vegano', 'proteico', 'café da manhã'],
    '{"Proteínas": "15g", "Carboidratos": "10g", "Gorduras": "10g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Vegano']
);

-- Receita 37: Molho Pesto
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Molho Pesto',
    'Molho versátil e aromático',
    'Molhos',
    'https://images.unsplash.com/photo-1626200419199-391ae4be7a41',
    10,
    90,
    4,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de manjericão fresco',
        '1/4 xícara de castanha de caju',
        '1/4 xícara de azeite de oliva',
        '1 dente de alho',
        '1 colher de sopa de suco de limão',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Em um processador, bata o manjericão, castanhas, alho, suco de limão e azeite até formar uma pasta.',
        'Tempere com sal e pimenta.',
        'Sirva o molho pesto sobre massas integrais ou como acompanhamento de vegetais assados.'
    ],
    'Rico em antioxidantes e gorduras boas!',
    ARRAY['vegano', 'molho', 'aromático'],
    '{"Proteínas": "2g", "Carboidratos": "3g", "Gorduras": "8g", "Fibras": "1g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Almoço', 'Jantar'],
    ARRAY[]::TEXT[],
    ARRAY['Gorduras'],
    ARRAY['Vegano']
);

-- Receita 38: Mousse de Maracujá
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Mousse de Maracujá',
    'Sobremesa leve e refrescante',
    'Sobremesas',
    'https://images.unsplash.com/photo-1488477181946-6428a0291777',
    20,
    150,
    4,
    'Fácil',
    4.9,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY[
        '1 polpa de maracujá (sem sementes)',
        '1/2 xícara de iogurte grego natural sem açúcar',
        '1 colher de sopa de mel (opcional)',
        '1 colher de chá de gelatina incolor sem sabor',
        '3 colheres de sopa de água'
    ],
    ARRAY[
        'Dissolva a gelatina em 3 colheres de sopa de água quente e misture bem.',
        'Bata no liquidificador a polpa de maracujá, o iogurte e o mel até obter uma mistura homogênea.',
        'Adicione a gelatina dissolvida e bata mais um pouco.',
        'Distribua a mousse em taças e leve à geladeira por pelo menos 2 horas antes de servir.'
    ],
    'O maracujá tem propriedades calmantes naturais!',
    ARRAY['sobremesa light', 'refrescante', 'fácil'],
    '{"Proteínas": "5g", "Carboidratos": "20g", "Gorduras": "3g", "Fibras": "2g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Carboidratos'],
    ARRAY[]::TEXT[]
);

-- Receita 39: Muffin Salgado (Frango, Ovo, Tapioca, Requeijão Light)
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Muffin Salgado (Frango, Ovo, Tapioca, Requeijão Light)',
    'Muffin proteico e prático',
    'Lanches',
    'https://images.unsplash.com/photo-1607958996333-41aef7caefaa',
    30,
    180,
    6,
    'Fácil',
    4.7,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1 xícara de peito de frango desfiado',
        '1 ovo',
        '2 colheres de sopa de tapioca',
        '2 colheres de sopa de requeijão light',
        '1/2 cebola picada',
        '1 dente de alho picado',
        'Sal e pimenta a gosto'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C e unte uma forma de muffins.',
        'Refogue a cebola e o alho no azeite até ficarem macios, depois adicione o frango desfiado e tempere com sal e pimenta.',
        'Em uma tigela, misture o frango refogado, o ovo, a tapioca e o requeijão.',
        'Divida a mistura entre as forminhas de muffin e leve ao forno por 20-25 minutos, até dourar.',
        'Sirva quente como lanche ou refeição leve.'
    ],
    'Perfeito para preparar e congelar!',
    ARRAY['proteico', 'muffin', 'meal prep'],
    '{"Proteínas": "15g", "Carboidratos": "10g", "Gorduras": "8g", "Fibras": "1g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Salgado'],
    ARRAY['Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY['Funcional']
);

-- Receita 40: Muffin de Mirtilo (com proteína vegetal de baunilha)
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    nutritionist_tip,
    tags,
    nutritional_info,
    filter_goal,
    filter_taste,
    filter_meal,
    filter_timing,
    filter_nutrients,
    filter_other
) VALUES (
    'Muffin de Mirtilo (com proteína vegetal de baunilha)',
    'Muffin proteico e antioxidante',
    'Lanches',
    'https://images.unsplash.com/photo-1607958996333-41aef7caefaa',
    30,
    160,
    6,
    'Fácil',
    4.8,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY[
        '1/2 xícara de farinha de amêndoas',
        '1/2 xícara de proteína vegetal de baunilha',
        '1/4 xícara de mel ou adoçante natural',
        '1/4 xícara de leite de amêndoas',
        '1 ovo',
        '1/2 colher de chá de fermento em pó',
        '1/2 xícara de mirtilos frescos (ou congelados)'
    ],
    ARRAY[
        'Preaqueça o forno a 180°C e unte uma forma de muffins.',
        'Em uma tigela, misture a farinha de amêndoas, a proteína, o fermento e o adoçante.',
        'Em outra tigela, bata o ovo e adicione o leite de amêndoas e o mel.',
        'Combine os ingredientes secos com os molhados e misture até ficar homogêneo.',
        'Dobre os mirtilos na massa delicadamente.',
        'Divida a massa nas forminhas e asse por 20-25 minutos, até dourar.'
    ],
    'Mirtilos são ricos em antioxidantes!',
    ARRAY['proteico', 'antioxidante', 'muffin'],
    '{"Proteínas": "10g", "Carboidratos": "18g", "Gorduras": "6g", "Fibras": "3g"}'::jsonb,
    ARRAY['Emagrecimento'],
    ARRAY['Doce'],
    ARRAY['Café da Manhã', 'Lanche da Tarde'],
    ARRAY[]::TEXT[],
    ARRAY['Proteínas'],
    ARRAY[]::TEXT[]
); 