-- Receitas reais da Bruna Braga extraídas do documento oficial
-- Gerado automaticamente em 2025-07-16 11:02:11.737269

-- Limpar receitas mockadas existentes
DELETE FROM recipes WHERE author_name = 'Bruna Braga' OR author_name = 'Dra. Maria Silva';

-- Receita 1: Bolo de Banana de Caneca
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Bolo de Banana de Caneca',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1558303420-f814d8a590f5',
    5,
    200,
    1,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY['1 banana madura'],
    ARRAY['Amasse a banana e misture com o ovo, aveia, fermento e mel.'],
    ARRAY['Emagrecimento', 'Doce', 'Café da Manhã', 'Lanche da Tarde', 'Carboidratos'],
    NOW(),
    NOW()
);

-- Receita 2: Banana Toast
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Banana Toast',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1565299543923-37dd37887442',
    10,
    250,
    1,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY['1 banana fatiada'],
    ARRAY['Coloque o pão de forma na airfryer e toste por 4 minutos a 180°C.'],
    ARRAY['Emagrecimento', 'Doce', 'Café da Manhã', 'Lanche da Tarde', 'Carboidratos'],
    NOW(),
    NOW()
);

-- Receita 3: Gororoba de Banana
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Gororoba de Banana',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1571091718767-18b5b1457add',
    10,
    300,
    1,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY['1 banana madura'],
    ARRAY['Em uma frigideira, bata os ovos e acrescente os ingredientes restantes.'],
    ARRAY['Emagrecimento', 'Doce', 'Café da Manhã', 'Lanche da Tarde', 'Proteínas'],
    NOW(),
    NOW()
);

-- Receita 4: Pão de Queijo de Airfryer
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Pão de Queijo de Airfryer',
    'Ideal para emagrecimento, Rico em proteínas.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e',
    15,
    180,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY['1 xícara de polvilho doce'],
    ARRAY['Misture todos os ingredientes até formar uma massa homogênea.'],
    ARRAY['Emagrecimento', 'Hipertrofia', 'Salgado', 'Café da Manhã', 'Proteínas'],
    NOW(),
    NOW()
);

-- Receita 5: Tortinha de Frango de Airfryer
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Tortinha de Frango de Airfryer',
    'Ideal para emagrecimento, Rico em proteínas.',
    'Almoço',
    'https://images.unsplash.com/photo-1574894709920-11b28e7367e3',
    25,
    250,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    true,
    ARRAY['200g de peito de frango desfiado'],
    ARRAY['Misture o frango, ovo, queijo e batata amassada.'],
    ARRAY['Emagrecimento', 'Hipertrofia', 'Salgado', 'Almoço', 'Jantar', 'Proteínas'],
    NOW(),
    NOW()
);

-- Receita 6: Bolo Alagado
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Bolo Alagado',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1578985545062-69928b1d9587',
    30,
    250,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 ovos'],
    ARRAY['Misture os ovos com o whey e o cacau até formar uma massa homogênea.'],
    ARRAY['Emagrecimento', 'Doce', 'Café da Manhã', 'Lanche da Tarde', 'Carboidratos'],
    NOW(),
    NOW()
);

-- Receita 7: Panqueca de Espinafre e Atum
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Panqueca de Espinafre e Atum',
    'Ideal para emagrecimento.',
    'Almoço',
    'https://images.unsplash.com/photo-1606787620819-8bdf0c44c293',
    15,
    220,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 ovos'],
    ARRAY['Misture todos os ingredientes e cozinhe em uma frigideira antiaderente até dourar dos dois lados.'],
    ARRAY['Emagrecimento', 'Proteínas', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 8: Smoothie de Frutas Vermelhas e Whey Protein
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Smoothie de Frutas Vermelhas e Whey Protein',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1553530666-ba11a90bb0b1',
    5,
    200,
    1,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1/2 xícara de frutas vermelhas congeladas'],
    ARRAY['Bata todos os ingredientes no liquidificador até ficar homogêneo.'],
    ARRAY['Emagrecimento', 'Doce', 'Pós Treino', 'Lanche da Tarde'],
    NOW(),
    NOW()
);

-- Receita 9: Abobrinha Recheada com Frango e Creme de Ricota
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Abobrinha Recheada com Frango e Creme de Ricota',
    'Ideal para emagrecimento, Rico em proteínas.',
    'Almoço',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    30,
    280,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 abobrinhas médias'],
    ARRAY['Corte as abobrinhas ao meio e retire o miolo.'],
    ARRAY['Emagrecimento', 'Hipertrofia', 'Salgado', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 10: Aveioca
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Aveioca',
    'Ideal para emagrecimento, Rico em proteínas.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    10,
    180,
    1,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 ovo'],
    ARRAY['Misture todos os ingredientes e cozinhe em uma frigideira até dourar dos dois lados.'],
    ARRAY['Emagrecimento', 'Hipertrofia', 'Salgado', 'Café da Manhã'],
    NOW(),
    NOW()
);

-- Receita 11: Barrinha de Proteína Artesanal
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Barrinha de Proteína Artesanal',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1606756790138-261d2b21cd75',
    20,
    150,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de aveia'],
    ARRAY['Misture todos os ingredientes até formar uma massa homogênea.'],
    ARRAY['Emagrecimento', 'Pós Treino', 'Lanche da Tarde', 'Proteínas'],
    NOW(),
    NOW()
);

-- Receita 12: Beijinho Saudável
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Beijinho Saudável',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1559656914-a30970c1affd',
    15,
    80,
    10,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de coco ralado sem açúcar'],
    ARRAY['Misture todos os ingredientes até formar uma massa homogênea.'],
    ARRAY['Emagrecimento', 'Doce', 'Lanche da Tarde'],
    NOW(),
    NOW()
);

-- Receita 13: Berinjela Recheada
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Berinjela Recheada',
    'Ideal para emagrecimento.',
    'Almoço',
    'https://images.unsplash.com/photo-1586190848861-99aa4a171e90',
    30,
    250,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 berinjelas médias'],
    ARRAY['Corte as berinjelas ao meio e retire o miolo.'],
    ARRAY['Emagrecimento', 'Salgado', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 14: Biscoito de Banana com Passas
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Biscoito de Banana com Passas',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1499636136210-6f4ee915583e',
    15,
    120,
    12,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 bananas maduras amassadas'],
    ARRAY['Misture todos os ingredientes até formar uma massa.'],
    ARRAY['Emagrecimento', 'Doce', 'Lanche da Tarde'],
    NOW(),
    NOW()
);

-- Receita 15: Bolinho de Prestígio
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Bolinho de Prestígio',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1571115764595-644a1f56a55c',
    25,
    150,
    8,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de coco ralado sem açúcar'],
    ARRAY['Misture todos os ingredientes até formar uma massa homogênea.'],
    ARRAY['Emagrecimento', 'Doce', 'Lanche da Tarde'],
    NOW(),
    NOW()
);

-- Receita 16: Bolo de Maçã com Canela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Bolo de Maçã com Canela',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1587040307369-da47b9d1e2b9',
    40,
    180,
    8,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 maçãs picadas'],
    ARRAY['Misture todos os ingredientes em uma tigela até formar uma massa homogênea.'],
    ARRAY['Emagrecimento', 'Doce', 'Café da Manhã', 'Lanche da Tarde'],
    NOW(),
    NOW()
);

-- Receita 17: Bolo de Laranja com Casca
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Bolo de Laranja com Casca',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1506459225024-1428097a7e18',
    30,
    200,
    8,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 laranjas médias (com casca)'],
    ARRAY['Bata as laranjas com casca no liquidificador até obter um suco espesso.'],
    ARRAY['Emagrecimento', 'Doce', 'Café da Manhã', 'Lanche da Tarde'],
    NOW(),
    NOW()
);

-- Receita 18: Caldo Verde
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Caldo Verde',
    'Ideal para emagrecimento.',
    'Jantar',
    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136',
    30,
    150,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['300g de batata doce'],
    ARRAY['Cozinhe a batata doce até amolecer.'],
    ARRAY['Emagrecimento', 'Sopa', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 19: Caldo de Abóbora
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Caldo de Abóbora',
    'Ideal para emagrecimento.',
    'Jantar',
    'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a',
    30,
    180,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['500g de abóbora'],
    ARRAY['Cozinhe a abóbora até amolecer.'],
    ARRAY['Emagrecimento', 'Sopa', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 20: Caldo de Legumes
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Caldo de Legumes',
    'Ideal para emagrecimento.',
    'Jantar',
    'https://images.unsplash.com/photo-1547592180-85f173990554',
    30,
    120,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 cenoura'],
    ARRAY['Corte os legumes em cubos e cozinhe no caldo de legumes até amolecerem.'],
    ARRAY['Emagrecimento', 'Sopa', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 21: Caponata de Berinjela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Caponata de Berinjela',
    'Ideal para emagrecimento, 100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1599599810769-bcde5a160d32',
    40,
    150,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 berinjelas médias picadas'],
    ARRAY['Aqueça o azeite em uma panela grande e refogue a cebola até dourar.'],
    ARRAY['Emagrecimento', 'Vegano', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 22: Chips de Batata Doce
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Chips de Batata Doce',
    'Ideal para emagrecimento, 100% vegano.',
    'Lanches',
    'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5',
    30,
    120,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 batatas doces médias'],
    ARRAY['Preaqueça o forno a 180°C e forre uma assadeira com papel manteiga.'],
    ARRAY['Emagrecimento', 'Lanche', 'Vegano'],
    NOW(),
    NOW()
);

-- Receita 23: Snacks de Grão de Bico
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Snacks de Grão de Bico',
    'Ideal para emagrecimento, 100% vegano.',
    'Lanches',
    'https://images.unsplash.com/photo-1599909533318-9e40d38eac4c',
    40,
    140,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de grão de bico cozido'],
    ARRAY['Preaqueça o forno a 200°C e forre uma assadeira com papel manteiga.'],
    ARRAY['Emagrecimento', 'Lanche', 'Vegano'],
    NOW(),
    NOW()
);

-- Receita 24: Coxinha Funcional de Frango com Creme de Queijo Cottage
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Coxinha Funcional de Frango com Creme de Queijo Cottage',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1612874742237-6526221588e3',
    1,
    180,
    8,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['300g de peito de frango cozido e desfiado'],
    ARRAY['Refogue a cebola e o alho no azeite até dourarem.'],
    ARRAY['Emagrecimento', 'Proteínas', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 25: Crepe de Beterraba
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Crepe de Beterraba',
    'Ideal para emagrecimento, 100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    25,
    140,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 beterraba pequena ralada'],
    ARRAY['Misture a beterraba ralada, farinha de grão-de-bico, água, azeite, sal e pimenta.'],
    ARRAY['Emagrecimento', 'Vegano', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 26: Espaguete de Abobrinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Espaguete de Abobrinha',
    'Ideal para emagrecimento, 100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1556909114-35b83eb5f96d',
    15,
    100,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 abobrinhas médias'],
    ARRAY['Use um espiralizador para fazer o espaguete de abobrinha.'],
    ARRAY['Emagrecimento', 'Vegano', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 27: Falafel de Forno
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Falafel de Forno',
    'Ideal para emagrecimento, 100% vegano.',
    'Lanches',
    'https://images.unsplash.com/photo-1593504049359-74330189a345',
    40,
    150,
    12,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de grão de bico cozido'],
    ARRAY['No processador de alimentos, bata o grão de bico, cebola, alho, cominho, coentro, azeite e farinha até formar uma massa.'],
    ARRAY['Emagrecimento', 'Vegano', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 28: Granola Caseira
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Granola Caseira',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38',
    30,
    180,
    8,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 xícaras de aveia em flocos'],
    ARRAY['Preaqueça o forno a 180°C e forre uma assadeira com papel manteiga.', 'Misture todos os ingredientes secos em uma tigela grande.', 'Em uma tigela pequena, misture o mel, o óleo de coco e a baunilha.', 'Adicione os ingredientes líquidos à mistura seca e misture bem.', 'Espalhe a mistura na assadeira de maneira uniforme e asse por 20-25 minutos, mexendo na metade do tempo, até dourar.', 'Deixe esfriar completamente antes de armazenar em um recipiente hermético.'],
    ARRAY['Emagrecimento', 'Lanche', 'Café da manhã'],
    NOW(),
    NOW()
);

-- Receita 29: Gratinado Light de Frango
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Gratinado Light de Frango',
    'Ideal para emagrecimento.',
    'Almoço',
    'https://images.unsplash.com/photo-1574894709920-11b28e7367e3',
    40,
    250,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['500g de peito de frango cozido e desfiado'],
    ARRAY['Preaqueça o forno a 180°C.', 'Refogue a cebola e o alho no azeite até dourarem.', 'Adicione o frango desfiado e cozinhe por 5 minutos.', 'Misture o creme de leite, o queijo parmesão e a muçarela, temperando com sal e pimenta.', 'Transfira a mistura para um refratário, cubra com queijo e leve ao forno por 15 minutos ou até dourar.'],
    ARRAY['Emagrecimento', 'Proteínas', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 30: Grãomelete (Omelete de Grão de Bico)
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Grãomelete (Omelete de Grão de Bico)',
    'Ideal para emagrecimento, 100% vegano.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445',
    15,
    180,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de farinha de grão de bico'],
    ARRAY['Em uma tigela, misture a farinha de grão de bico com água até formar uma massa espessa.', 'Aqueça o azeite em uma frigideira e refogue a cebola e o tomate até ficarem macios.', 'Adicione a mistura de farinha de grão de bico, cúrcuma, sal e pimenta e cozinhe por 5-7 minutos de cada lado até dourar.', 'Sirva quente com vegetais ou molho de sua preferência.'],
    ARRAY['Emagrecimento', 'Vegano', 'Café da manhã', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 31: Hambúrguer Caseiro
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Hambúrguer Caseiro',
    'Ideal para emagrecimento.',
    'Almoço',
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    30,
    350,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['500g de carne de patinho moída'],
    ARRAY['Em uma tigela, misture a carne moída, cebola, alho, ovo, azeite, sal e pimenta.', 'Modele a mistura em 4 hambúrgueres e reserve.', 'Aqueça uma frigideira e cozinhe os hambúrgueres por 4-5 minutos de cada lado, até dourar.', 'Monte os hambúrgueres nos pães, adicionando uma fatia de queijo e os vegetais.'],
    ARRAY['Emagrecimento', 'Proteínas', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 32: Lasanha de Berinjela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Lasanha de Berinjela',
    'Ideal para emagrecimento, 100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f',
    1,
    180,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 berinjelas grandes cortadas em fatias finas'],
    ARRAY['Preaqueça o forno a 180°C.', 'Grelhe as fatias de berinjela em uma frigideira com um pouco de azeite até ficarem douradas.', 'Em uma tigela, misture o tofu ou ricota com o espinafre, sal e pimenta.', 'Monte a lasanha em um refratário, alternando camadas de berinjela, molho de tomate e a mistura de tofu/ricota.', 'Finalize com o queijo parmesão e leve ao forno por 30 minutos.'],
    ARRAY['Emagrecimento', 'Vegano', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 33: Lasanha de Abobrinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Lasanha de Abobrinha',
    'Ideal para emagrecimento, 100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1556909114-35b83eb5f96d',
    1,
    160,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 abobrinhas cortadas em fatias finas'],
    ARRAY['Preaqueça o forno a 180°C.', 'Grelhe as fatias de abobrinha em uma frigideira com azeite até ficarem douradas.', 'Em uma tigela, misture o tofu ou ricota com espinafre, sal e pimenta.', 'Monte a lasanha alternando camadas de abobrinha, molho de tomate e a mistura de tofu/ricota.', 'Leve ao forno por 30 minutos, até dourar.'],
    ARRAY['Emagrecimento', 'Vegano', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 34: Mexido de Tofu
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Mexido de Tofu',
    'Ideal para emagrecimento, 100% vegano.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1546833999-b9f581a1996d',
    15,
    180,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['200g de tofu firme'],
    ARRAY['Aqueça o azeite em uma frigideira e refogue a cebola, o alho e o pimentão até ficarem macios.', 'Esfarele o tofu com as mãos e adicione à frigideira.', 'Adicione o tomate, a cúrcuma, o sal e a pimenta e cozinhe por 5-7 minutos, mexendo ocasionalmente.', 'Sirva quente, com uma fatia de pão integral ou salada.'],
    ARRAY['Vegano', 'Emagrecimento', 'Café da manhã', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 35: Molho Pesto
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Molho Pesto',
    'Ideal para emagrecimento, 100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1572441713132-5b65d3ea9b2d',
    10,
    90,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de manjericão fresco'],
    ARRAY['Em um processador, bata o manjericão, castanhas, alho, suco de limão e azeite até formar uma pasta.', 'Tempere com sal e pimenta.', 'Sirva o molho pesto sobre massas integrais ou como acompanhamento de vegetais assados.'],
    ARRAY['Vegano', 'Emagrecimento', 'Almoço', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 36: Mousse de Maracujá
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Mousse de Maracujá',
    'Ideal para emagrecimento.',
    'Sobremesas',
    'https://images.unsplash.com/photo-1488900128323-21503983a07e',
    20,
    150,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 polpa de maracujá (sem sementes)'],
    ARRAY['Dissolva a gelatina em 3 colheres de sopa de água quente e misture bem.', 'Bata no liquidificador a polpa de maracujá, o iogurte e o mel até obter uma mistura homogênea.', 'Adicione a gelatina dissolvida e bata mais um pouco.', 'Distribua a mousse em taças e leve à geladeira por pelo menos 2 horas antes de servir.'],
    ARRAY['Emagrecimento', 'Sobremesa'],
    NOW(),
    NOW()
);

-- Receita 37: Muffin Salgado (Frango, Ovo, Tapioca, Requeijão Light)
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Muffin Salgado (Frango, Ovo, Tapioca, Requeijão Light)',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13',
    30,
    180,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de peito de frango desfiado'],
    ARRAY['Preaqueça o forno a 180°C e unte uma forma de muffins.', 'Refogue a cebola e o alho no azeite até ficarem macios, depois adicione o frango desfiado e tempere com sal e pimenta.', 'Em uma tigela, misture o frango refogado, o ovo, a tapioca e o requeijão.', 'Divida a mistura entre as forminhas de muffin e leve ao forno por 20-25 minutos, até dourar.', 'Sirva quente como lanche ou refeição leve.'],
    ARRAY['Emagrecimento', 'Proteínas', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 38: Muffin de Mirtilo (com proteína vegetal de baunilha)
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Muffin de Mirtilo (com proteína vegetal de baunilha)',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1506459225024-1428097a7e18',
    30,
    160,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1/2 xícara de farinha de amêndoas'],
    ARRAY['Preaqueça o forno a 180°C e unte uma forma de muffins.', 'Em uma tigela, misture a farinha de amêndoas, a proteína, o fermento e o adoçante.', 'Em outra tigela, bata o ovo e adicione o leite de amêndoas e o mel.', 'Combine os ingredientes secos com os molhados e misture até ficar homogêneo.', 'Dobre os mirtilos na massa delicadamente.', 'Divida a massa nas forminhas e asse por 20-25 minutos, até dourar.'],
    ARRAY['Emagrecimento', 'Proteínas', 'Lanche', 'Café da manhã'],
    NOW(),
    NOW()
);

-- Receita 39: Nhoque de Cenoura
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Nhoque de Cenoura',
    'Ideal para emagrecimento, Baixo em carboidratos.',
    'Almoço',
    'https://images.unsplash.com/photo-1556909114-35b83eb5f96d',
    40,
    120,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 cenouras médias cozidas e amassadas'],
    ARRAY['Cozinhe as cenouras até ficarem macias, depois amasse bem.', 'Em uma tigela, combine a cenoura amassada, a farinha de arroz, o amido de batata-doce, o ovo, o sal e a pimenta.', 'Misture até formar uma massa homogênea. Se necessário, adicione um pouco de água para dar a consistência ideal.', 'Modele os nhoques e cozinhe-os em água fervente com sal. Quando subirem à superfície, estão prontos.', 'Sirva com molho de sua preferência.'],
    ARRAY['Emagrecimento', 'Low Carb', 'Jantar', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 40: Nhoque de Mandioquinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Nhoque de Mandioquinha',
    'Ideal para emagrecimento, Baixo em carboidratos.',
    'Almoço',
    'https://images.unsplash.com/photo-1556909114-35b83eb5f96d',
    40,
    130,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 mandioquinhas médias cozidas e amassadas'],
    ARRAY['Cozinhe as mandioquinhas até ficarem macias, depois amasse bem.', 'Em uma tigela, combine a mandioquinha amassada, a farinha de arroz, o ovo, o azeite, o sal e a pimenta.', 'Misture até formar uma massa homogênea e, se necessário, adicione um pouco de água para dar a consistência ideal.', 'Modele os nhoques e cozinhe-os em água fervente com sal. Quando subirem à superfície, estão prontos.', 'Sirva com molho de sua preferência.'],
    ARRAY['Emagrecimento', 'Low Carb', 'Jantar', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 41: Nuggets de Frango Funcional
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Nuggets de Frango Funcional',
    'Ideal para emagrecimento.',
    'Jantar',
    'https://images.unsplash.com/photo-1562967914-608f82629710',
    30,
    180,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['300g de peito de frango moído'],
    ARRAY['Em uma tigela, misture o frango moído, o ovo, o farelo de aveia, o queijo parmesão, o alho, o sal e a pimenta.', 'Modele a mistura em pequenos pedaços no formato de nuggets.', 'Coloque-os em uma assadeira untada com azeite e asse a 180°C por cerca de 20-25 minutos, virando-os na metade do tempo para dourar por igual.', 'Sirva quente, acompanhado de molho de sua preferência.'],
    ARRAY['Proteínas', 'Emagrecimento', 'Lanche', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 42: Omelete de Forno
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Omelete de Forno',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1525351484163-7529414344d8',
    25,
    150,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['4 ovos'],
    ARRAY['Preaqueça o forno a 180°C e unte uma assadeira com azeite.', 'Em uma tigela, bata os ovos e misture os legumes e o queijo cottage. Tempere com sal e pimenta.', 'Despeje a mistura na assadeira e leve ao forno por 15-20 minutos, até que esteja firme e dourado por cima.', 'Sirva imediatamente, acompanhado de uma salada.'],
    ARRAY['Emagrecimento', 'Proteínas', 'Café da manhã', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 43: Panqueca de Cacau
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Panqueca de Cacau',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    15,
    120,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 banana madura'],
    ARRAY['Em um liquidificador ou tigela, bata a banana, o ovo, o cacau, a essência de baunilha e o leite.', 'Aqueça uma frigideira antiaderente e despeje pequenas porções da massa, formando as panquecas.', 'Cozinhe por 2-3 minutos de cada lado, até dourar.', 'Sirva com mel ou frutas frescas, se desejar.'],
    ARRAY['Emagrecimento', 'Café da manhã', 'Sobremesa'],
    NOW(),
    NOW()
);

-- Receita 44: Pão Caseiro sem Glúten
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Pão Caseiro sem Glúten',
    'Ideal para emagrecimento.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1549931319-a545dcf3bc73',
    1,
    120,
    12,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 xícaras de farinha de arroz'],
    ARRAY['Em uma tigela, misture a farinha de arroz, a fécula de batata, o fermento, o sal e o açúcar.', 'Adicione o azeite e a água morna aos poucos e misture até formar uma massa homogênea.', 'Deixe a massa descansar por 1 hora em um lugar morno.', 'Modele a massa em forma de pão e coloque em uma assadeira untada.', 'Leve ao forno preaquecido a 180°C por cerca de 40-45 minutos ou até dourar.'],
    ARRAY['Sem Glúten', 'Emagrecimento', 'Café da manhã'],
    NOW(),
    NOW()
);

-- Receita 45: Pastinha de Berinjela
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Pastinha de Berinjela',
    'Ideal para emagrecimento, 100% vegano.',
    'Lanches',
    'https://images.unsplash.com/photo-1599599810769-bcde5a160d32',
    25,
    90,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 berinjela média'],
    ARRAY['Corte a berinjela em cubos e cozinhe-a no vapor até ficar bem macia.', 'Em uma frigideira, refogue o alho no azeite até dourar, depois adicione a berinjela cozida e amasse-a com um garfo.', 'Tempere com suco de limão, sal e pimenta e mexa bem.', 'Finalize com salsinha picada e sirva como acompanhamento ou com torradas.'],
    ARRAY['Vegano', 'Emagrecimento', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 46: Patê de Frango
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Patê de Frango',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1574894709920-11b28e7367e3',
    15,
    130,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['200g de peito de frango cozido e desfiado'],
    ARRAY['Em uma frigideira, refogue a cebola no azeite até dourar.', 'Adicione o frango desfiado e misture bem.', 'Acrescente a mostarda, o requeijão, sal e pimenta. Misture até ficar homogêneo.', 'Transfira para um recipiente e leve à geladeira por 30 minutos antes de servir.'],
    ARRAY['Proteínas', 'Lanche', 'Emagrecimento'],
    NOW(),
    NOW()
);

-- Receita 47: Patê de Atum
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Patê de Atum',
    'Ideal para emagrecimento.',
    'Lanches',
    'https://images.unsplash.com/photo-1563379091339-03246963d24a',
    10,
    100,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 lata de atum em água, escorrido'],
    ARRAY['Em uma tigela, amasse o atum com um garfo.', 'Adicione o requeijão, o suco de limão, a mostarda, o sal e a pimenta.', 'Misture bem até ficar cremoso e homogêneo.', 'Sirva com torradas ou vegetais crus.'],
    ARRAY['Proteínas', 'Lanche', 'Emagrecimento'],
    NOW(),
    NOW()
);

-- Receita 48: Patê de Ricota com Alho
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Patê de Ricota com Alho',
    'Ideal para emagrecimento, 100% vegano.',
    'Lanches',
    'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d',
    10,
    90,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['200g de ricota amassada'],
    ARRAY['Em uma tigela, misture a ricota com o alho picado.', 'Adicione o azeite, sal, pimenta e a salsinha.', 'Misture bem até ficar homogêneo e sirva com biscoitos integrais ou vegetais.'],
    ARRAY['Vegano', 'Lanche', 'Emagrecimento'],
    NOW(),
    NOW()
);

-- Receita 49: Picolé de Frutas
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Picolé de Frutas',
    'Ideal para emagrecimento, Baixo em carboidratos.',
    'Sobremesas',
    'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f',
    10,
    50,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 banana madura'],
    ARRAY['Bata todos os ingredientes no liquidificador até ficar homogêneo.', 'Despeje a mistura em forminhas de picolé.', 'Leve ao congelador por 4-6 horas ou até ficarem firmes.', 'Retire da forma e sirva.'],
    ARRAY['Low Carb', 'Sobremesa', 'Emagrecimento'],
    NOW(),
    NOW()
);

-- Receita 50: Sorvete de Iogurte com Whey
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Sorvete de Iogurte com Whey',
    'Receita saudável e nutritiva.',
    'Sobremesas',
    'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f',
    10,
    140,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de iogurte grego natural sem açúcar'],
    ARRAY['Em uma tigela, misture o iogurte, o whey, o mel e a essência de baunilha.', 'Despeje a mistura em um recipiente próprio para congelar e leve ao congelador por 3-4 horas.', 'Retire do congelador e deixe descansar por alguns minutos antes de servir.'],
    ARRAY['Proteínas', 'Sobremesa', 'Pós-treino'],
    NOW(),
    NOW()
);

-- Receita 51: Sorbet de Morango e Banana
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Sorbet de Morango e Banana',
    'Baixo em carboidratos, 100% vegano.',
    'Sobremesas',
    'https://images.unsplash.com/photo-1488900128323-21503983a07e',
    10,
    80,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 banana madura congelada'],
    ARRAY['Coloque os morangos, a banana, o mel e o suco de limão em um processador de alimentos.', 'Processe até ficar com uma consistência cremosa, similar a um sorvete.', 'Se necessário, adicione um pouco de água para ajudar a bater.', 'Sirva imediatamente ou leve ao congelador para firmar mais.'],
    ARRAY['Vegano', 'Low Carb', 'Sobremesa'],
    NOW(),
    NOW()
);

-- Receita 52: Pizza de Clara de Ovo com Recheio de Frango Desfiado, Queijo, Tomate e Manjericão
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Pizza de Clara de Ovo com Recheio de Frango Desfiado, Queijo, Tomate e Manjericão',
    'Baixo em carboidratos.',
    'Jantar',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    25,
    180,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['4 claras de ovo'],
    ARRAY['Preaqueça o forno a 180°C.', 'Bata as claras de ovo com sal e pimenta até ficarem firmes.', 'Em uma frigideira antiaderente untada com azeite, despeje as claras batidas e deixe dourar como uma base de pizza.', 'Após dourar, cubra a base com o frango desfiado, o queijo, os tomates e o manjericão.', 'Leve ao forno por 5-7 minutos até o queijo derreter. Sirva imediatamente.'],
    ARRAY['Proteínas', 'Jantar', 'Low Carb'],
    NOW(),
    NOW()
);

-- Receita 53: Queijo de Castanhas
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Queijo de Castanhas',
    '100% vegano.',
    'Lanches',
    'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d',
    15,
    160,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de castanha de caju crua (deixe de molho por 4 horas)'],
    ARRAY['Escorra as castanhas de caju e coloque no processador de alimentos.', 'Adicione a água, a levedura nutricional, o suco de limão, o alho, o sal e a pimenta.', 'Processe até obter uma consistência cremosa e homogênea.', 'Transfira para um recipiente e leve à geladeira por pelo menos 4 horas para firmar.', 'Sirva como patê ou acompanhando pães integrais.'],
    ARRAY['Vegano', 'Proteínas', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 54: Quiche de Alho-Poró e Tofu
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Quiche de Alho-Poró e Tofu',
    'Baixo em carboidratos, 100% vegano.',
    'Jantar',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    40,
    180,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 alho-poró cortado em rodelas finas'],
    ARRAY['Preaqueça o forno a 180°C.', 'Refogue o alho-poró no azeite até ficar macio.', 'Em um processador de alimentos, bata o tofu, a farinha de grão de bico, o leite de amêndoas, a cúrcuma, o sal e a pimenta até ficar uma mistura cremosa.', 'Acrescente o alho-poró refogado e misture bem.', 'Se desejar, coloque a mistura em uma forma de torta com massa pronta.', 'Leve ao forno por 25-30 minutos ou até a superfície dourar.'],
    ARRAY['Vegano', 'Low Carb', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 55: Quiche Funcional
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Quiche Funcional',
    'Baixo em carboidratos.',
    'Jantar',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    40,
    220,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['3 ovos'],
    ARRAY['Preaqueça o forno a 180°C.', 'Bata os ovos com o creme de leite e a cúrcuma até misturar bem.', 'Adicione o espinafre cozido, o queijo, a farinha de amêndoas, o sal e a pimenta.', 'Coloque a mistura em uma forma de torta com massa integral (se desejar).', 'Asse por 25-30 minutos ou até dourar e ficar firme.'],
    ARRAY['Funcional', 'Low Carb', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 56: Ragu de Cogumelos
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Ragu de Cogumelos',
    'Baixo em carboidratos, 100% vegano.',
    'Jantar',
    'https://images.unsplash.com/photo-1527156231393-7023794f363c',
    25,
    150,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['300g de cogumelos (shiitake, champignon ou o de sua preferência)'],
    ARRAY['Em uma frigideira, refogue a cebola e o alho no azeite até ficarem dourados.', 'Acrescente os cogumelos e refogue por mais 5 minutos.', 'Adicione o molho de tomate e o molho shoyu, misture bem e cozinhe por mais 10 minutos em fogo baixo.', 'Tempere com sal e pimenta a gosto.', 'Decore com salsinha e sirva quente, acompanhado de arroz integral ou vegetais assados.'],
    ARRAY['Vegano', 'Low Carb', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 57: Ravioli de Abobrinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Ravioli de Abobrinha',
    'Baixo em carboidratos, 100% vegano.',
    'Jantar',
    'https://images.unsplash.com/photo-1556909114-35b83eb5f96d',
    30,
    90,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 abobrinha média cortada em fatias finas (como lâminas de ravioli)'],
    ARRAY['Corte a abobrinha em lâminas finas no sentido do comprimento.', 'Em uma frigideira, refogue o alho no azeite até dourar, adicione a ricota (ou queijo cottage) e misture bem.', 'Coloque uma colher de sopa do recheio de ricota entre duas lâminas de abobrinha, formando os raviolis.', 'Cozinhe os raviolis em água fervente por 3-4 minutos.', 'Sirva com molho de tomate fresco ou pesto.'],
    ARRAY['Low Carb', 'Vegano', 'Jantar'],
    NOW(),
    NOW()
);

-- Receita 58: Salada de Atum Tropical
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Salada de Atum Tropical',
    'Baixo em carboidratos.',
    'Almoço',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    15,
    250,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 lata de atum em água (escorrido)'],
    ARRAY['Em uma tigela, combine o atum, a manga, o abacate e a cebola roxa.', 'Regue com o azeite e o suco de limão.', 'Tempere com sal e pimenta.', 'Sirva sobre folhas de alface frescas e decore com ervas a gosto, como coentro ou salsinha.'],
    ARRAY['Low Carb', 'Proteína', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 59: Salada de Pepino Oriental
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Salada de Pepino Oriental',
    'Baixo em carboidratos, 100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    10,
    120,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 pepinos fatiados finamente'],
    ARRAY['Em uma tigela, misture o pepino fatiado com o vinagre de arroz, molho de soja e óleo de gergelim.', 'Adicione o alho picado e mexa bem.', 'Polvilhe as sementes de gergelim e tempere com pimenta a gosto.', 'Sirva gelado como acompanhamento ou prato leve.'],
    ARRAY['Vegano', 'Low Carb', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 60: Salada Proteica
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Salada Proteica',
    'Receita saudável e nutritiva.',
    'Almoço',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    10,
    300,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 peito de frango grelhado e fatiado'],
    ARRAY['Em uma tigela grande, combine o frango grelhado, o grão-de-bico, pepino, tomate e cebola roxa.', 'Regue com azeite e suco de limão.', 'Tempere com sal e pimenta.', 'Misture bem e sirva imediatamente.'],
    ARRAY['Proteína', 'Almoço', 'Pós-treino'],
    NOW(),
    NOW()
);

-- Receita 61: Salgado de Batata Doce e Frango
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Salgado de Batata Doce e Frango',
    'Baixo em carboidratos.',
    'Lanches',
    'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13',
    30,
    150,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 batatas doces médias cozidas e amassadas'],
    ARRAY['Amasse as batatas doces cozidas até formar um purê.', 'Refogue a cebola no azeite até dourar, adicione o frango desfiado e misture bem.', 'Acrescente a salsa, sal e pimenta a gosto.', 'Modele os salgados, recheando com o frango.', 'Passe os salgados no ovo batido e depois na farinha de aveia.', 'Asse em forno preaquecido a 180°C por 20-25 minutos, ou até dourar.'],
    ARRAY['Funcional', 'Low Carb', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 62: Snacks de Abobrinha
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Snacks de Abobrinha',
    'Baixo em carboidratos, 100% vegano.',
    'Lanches',
    'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5',
    25,
    120,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 abobrinhas médias cortadas em tiras'],
    ARRAY['Preaqueça o forno a 180°C.', 'Misture o azeite, alho em pó, cebola em pó, sal e pimenta.', 'Passe as tiras de abobrinha pela mistura e depois pela farinha de amêndoas.', 'Coloque as tiras em uma assadeira forrada com papel manteiga.', 'Asse por 20-25 minutos, virando as tiras na metade do tempo, até ficarem douradas e crocantes.'],
    ARRAY['Vegano', 'Low Carb', 'Lanche'],
    NOW(),
    NOW()
);

-- Receita 63: Strogonoff Saudável
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Strogonoff Saudável',
    'Receita saudável e nutritiva.',
    'Almoço',
    'https://images.unsplash.com/photo-1574894709920-11b28e7367e3',
    30,
    350,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['500g de peito de frango em cubos'],
    ARRAY['Em uma panela, refogue a cebola e o alho no azeite até ficarem dourados.', 'Adicione o frango e frite até dourar.', 'Acrescente os cogumelos e refogue por mais 5 minutos.', 'Adicione o molho de tomate, o creme de leite, a mostarda e o molho shoyu.', 'Cozinhe por 10 minutos até o molho engrossar.', 'Tempere com sal e pimenta a gosto e decore com salsinha antes de servir.'],
    ARRAY['Funcional', 'Proteína', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 64: Strogonoff Vegano
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Strogonoff Vegano',
    '100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1527156231393-7023794f363c',
    30,
    280,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de cogumelos frescos fatiados'],
    ARRAY['Em uma panela, refogue a cebola e o alho no azeite até dourar.', 'Adicione os cogumelos e refogue até murcharem.', 'Acrescente a proteína de soja e refogue por 5 minutos.', 'Adicione o molho de tomate, o creme de leite de coco, o molho shoyu e a mostarda.', 'Cozinhe por 10 minutos até o molho engrossar.', 'Tempere com sal e pimenta e finalize com salsinha picada.'],
    ARRAY['Vegano', 'Funcional', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 65: Suchá de Melancia, Gengibre e Limão
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Suchá de Melancia, Gengibre e Limão',
    'Propriedades detox.',
    'Receitas Gerais',
    'https://images.unsplash.com/photo-1551334787-21e6bd3ab135',
    5,
    50,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 fatias grandes de melancia'],
    ARRAY['Bata todos os ingredientes no liquidificador até obter uma mistura homogênea.', 'Sirva gelado, com gelo a gosto.', 'Se desejar, adoce com mel.'],
    ARRAY['Detox', 'Hidratante', 'Bebidas'],
    NOW(),
    NOW()
);

-- Receita 66: Suco Verde com Kiwi
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Suco Verde com Kiwi',
    'Propriedades detox.',
    'Receitas Gerais',
    'https://images.unsplash.com/photo-1610970881699-44a5587cabec',
    5,
    80,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 kiwi descascado'],
    ARRAY['Bata todos os ingredientes no liquidificador até ficar homogêneo.', 'Sirva imediatamente com gelo a gosto.'],
    ARRAY['Detox', 'Energizante', 'Bebidas'],
    NOW(),
    NOW()
);

-- Receita 67: Suco Verde Tradicional
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Suco Verde Tradicional',
    'Propriedades detox.',
    'Receitas Gerais',
    'https://images.unsplash.com/photo-1610970881699-44a5587cabec',
    5,
    50,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 folha de couve'],
    ARRAY['Bata todos os ingredientes no liquidificador até ficar homogêneo.', 'Sirva imediatamente com gelo a gosto.'],
    ARRAY['Detox', 'Energizante', 'Bebidas'],
    NOW(),
    NOW()
);

-- Receita 68: Suflê de Legumes
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Suflê de Legumes',
    'Receita saudável e nutritiva.',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    40,
    180,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 abobrinha ralada'],
    ARRAY['Preaqueça o forno a 180°C.', 'Em uma frigideira, refogue a cebola no azeite até dourar, adicione a abobrinha e cenoura e cozinhe por 5 minutos.', 'Em um recipiente, bata os ovos, o leite, o queijo cottage, a farinha de aveia, sal e pimenta.', 'Misture os legumes refogados e a salsinha.', 'Coloque a mistura em uma assadeira untada e leve ao forno por 25 minutos ou até dourar.'],
    ARRAY['Funcional', 'Vegetariano', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 69: Suflê Vegano
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Suflê Vegano',
    '100% vegano.',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    40,
    150,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 xícara de couve-flor cozida'],
    ARRAY['Preaqueça o forno a 180°C.', 'Bata todos os ingredientes no liquidificador até formar um creme liso.', 'Transfira para uma assadeira untada e leve ao forno por 30 minutos ou até dourar.', 'Sirva quente e decore com salsinha picada.'],
    ARRAY['Vegano', 'Funcional', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 70: Tomate Recheado
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Tomate Recheado',
    'Receita saudável e nutritiva.',
    'Almoço',
    'https://images.unsplash.com/photo-1592924357228-91a4daadcfea',
    30,
    120,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['4 tomates grandes'],
    ARRAY['Preaqueça o forno a 180°C.', 'Corte a parte superior dos tomates e retire as sementes.', 'Em uma tigela, misture o arroz integral, o queijo parmesão, o alho, o azeite, sal e pimenta.', 'Recheie os tomates com a mistura e coloque-os em uma assadeira.', 'Leve ao forno por 20 minutos e sirva com manjericão fresco.'],
    ARRAY['Funcional', 'Vegetariano', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 71: Batata Recheada
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Batata Recheada',
    'Receita saudável e nutritiva.',
    'Almoço',
    'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5',
    45,
    250,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['4 batatas médias'],
    ARRAY['Cozinhe as batatas até ficarem macias e depois corte-as ao meio, retirando um pouco do miolo.', 'Refogue a cebola no azeite até dourar, adicione o frango desfiado, o queijo cottage, sal e pimenta.', 'Recheie as batatas com a mistura de frango e leve ao forno a 180°C por 15 minutos.', 'Decore com salsinha antes de servir.'],
    ARRAY['Funcional', 'Proteína', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 72: Torta de Liquidificador Super Rápida
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Torta de Liquidificador Super Rápida',
    'Receita saudável e nutritiva.',
    'Almoço',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b',
    30,
    180,
    6,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['2 ovos'],
    ARRAY['Preaqueça o forno a 180°C.', 'Bata todos os ingredientes no liquidificador até formar uma mistura homogênea.', 'Despeje a massa em uma forma untada e leve ao forno por 20 minutos ou até dourar.'],
    ARRAY['Funcional', 'Rápido', 'Almoço'],
    NOW(),
    NOW()
);

-- Receita 73: Waffle Funcional
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Waffle Funcional',
    'Receita saudável e nutritiva.',
    'Café da Manhã',
    'https://images.unsplash.com/photo-1562376552-0d160a2f238d',
    15,
    200,
    2,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['1 banana madura amassada'],
    ARRAY['Preaqueça a máquina de waffle.', 'Misture todos os ingredientes em uma tigela até formar uma massa homogênea.', 'Coloque a massa na máquina de waffle e cozinhe até ficar dourado.', 'Sirva com mel ou frutas frescas.'],
    ARRAY['Funcional', 'Café da manhã', 'Proteína'],
    NOW(),
    NOW()
);

-- Receita 74: Yakisoba Light
INSERT INTO recipes (
    title,
    description,
    category,
    image_url,
    preparation_time_minutes,
    calories,
    servings,
    difficulty,
    rating,
    content_type,
    author_name,
    author_type,
    is_featured,
    ingredients,
    instructions,
    tags,
    created_at,
    updated_at
) VALUES (
    'Yakisoba Light',
    'Receita saudável e nutritiva.',
    'Almoço',
    'https://images.unsplash.com/photo-1556909114-35b83eb5f96d',
    30,
    280,
    4,
    'Fácil',
    4.5,
    'text',
    'Bruna Braga',
    'nutritionist',
    false,
    ARRAY['200g de peito de frango cortado em tiras'],
    ARRAY['Em uma frigideira grande, refogue a cebola no óleo de gergelim até dourar.', 'Adicione o frango e refogue até dourar.', 'Junte a cenoura, o pimentão e refogue por mais 5 minutos.', 'Acrescente o macarrão, o molho shoyu e a cebolinha.', 'Misture bem e sirva quente.'],
    ARRAY['Funcional', 'Light', 'Almoço'],
    NOW(),
    NOW()
);

